### PR TITLE
Update cloud_server_using_nextcloud.md

### PR DESCRIPTION
**Pull request by jahway603**
I needed to add php for instructions about zip install for it to create the /etc/php.ini
OS: RockyLinux 8.7

#### Author checklist (Completed by original Author)
- [X] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [X] If applicable, steps and instructions have been tested to work
- [X] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@jahway603 I apologize! I didn't see this and was doing the rewrite of the entire procedure this morning and just merged that (as promised from the conversation in your forum post). `php` should install with the `php80-php` from the REMI repository. Do you need PHP from Rocky as well?

**Comment by sspencerwire** [comment]
@all-contributers add @jahway603 for content

**Comment by sspencerwire** [comment]
@all-contributors please add @jahway603 for content

**Comment by sspencerwire** [comment]
@jahway603 I'm guessing that you couldn't find the `php.ini` file in /etc and this is why you thought it necessary to install `php`... if that is the case, the path to the `php.ini` file is now corrected.

**Comment by jahway603** [comment]
@sspencerwire The rewrite looks great. That's correct that I couldn't find the php.ini as it was in the documentation.

**Comment by sspencerwire** [comment]
@jahway603 since this should now be fixed, I'll close your PR, but thank you for being involved!!

**Pull request closed without merging**
