### PR TITLE
New gemstone for determining kernel configs

### PR DESCRIPTION
**Pull request by NezSez**
#### Author checklist (Completed by original Author)
- [x] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [ ] Is this a non-English contribution? 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Check that document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Basic Editorial Review)
- [x] 4th Pass (Detailed Editorial Review and Peer Review)
- [x] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by NezSez** [comment]
Please convert this to a draft until I can verify the last statement on some distribution which actually has the `configs` option installed, or I can compile and test a RL kernel with it enabled.

**Comment by EzequielBruni** [comment]
> Please convert this to a draft until I can verify the last statement on some distribution which actually has the `configs` option installed, or I can compile and test a RL kernel with it enabled.

It actually shows up as a draft to me. Couldn't merge it if I wanted to... unless I made it not a draft. I'll leave it as-is.

**Comment by NezSez** [comment]
It does still show as a draft. I'd think it would stop the checks when in draft mode though and they are still running.

**Review by wsoyinka — APPROVED** [review]

**Comment by wsoyinka** [comment]
Looks great @NezSez !

**Comment by NezSez** [comment]
Should I just mark my PR ready to review...it's going to take a long time before I can verify that the line
`ls /sys/module/configs`
is correct (it should be, but finding a distro that actually uses configs mod by default is a problem).
I have a few more notes to make, then it should be ready.

**Comment by NezSez** [comment]
So the checkbox for "Is this a non-English contribution?" is a check that you checked if it was, rather than indicating that it is then?

**Comment by sspencerwire** [comment]
> So the checkbox for "Is this a non-English contribution?" is a check that you checked if it was non-english or not, rather than indicating that the submission actually _is_ non-english? If I don't check it, all tests will not pass, but if I do check it so the tests will complete, does any CI/CD workflows actually do anything like hand it off to crowdin etc?

That is correct!

**Comment by sspencerwire** [comment]
> > So the checkbox for "Is this a non-English contribution?" is a check that you checked if it was non-english or not, rather than indicating that the submission actually _is_ non-english? If I don't check it, all tests will not pass, but if I do check it so the tests will complete, does any CI/CD workflows actually do anything like hand it off to crowdin etc?
> 
> That is correct!

Don't worry about the passing of the checks, as we can override that one.

**Comment by sspencerwire** [comment]
merging into an editing branch

**Pull request merged**
