### PR TITLE
installation.md: improve grammar in a note

### PR DESCRIPTION
**Pull request by zdover23**
Reword the English in a the note that directs the reader to the Rocky ISO mirrors, so that the note reads better.

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [ x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by zdover23** [comment]
see also https://github.com/rocky-linux/documentation/pull/1503

**Review by sspencerwire — CHANGES_REQUESTED** [review]
Thanks @zdover23. It looks like this is now formatted on 3 separate lines, rather than on one line. I think that might be a problem, and probably wasn't your intent. Can you fix this before we merge? Also, admonitions need the 4 space indentation to stay within the note. Let me know if you have questions!

**Review by sspencerwire — APPROVED** [review]
I've fixed this one like the other one @zdover23 . Thank you again.

**Comment by zdover23** [comment]
> I've fixed this one like the other one @zdover23 . Thank you again.

I'll make more PRs over the weekend. It's 11 PM down here right now. I have a list of Ceph dependencies Rocky Linux is missing. Is there a place I can usefully report that?

**Pull request merged**
