### PR TITLE
rsync books,new dir

### PR DESCRIPTION
**Pull request by jimcat8**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [x] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@jimcat8 Don't do the .pages files. That's something that is required of editors. Also, did you mean to only submit the .pages file and then 3 .jpgs and that's it?  Weren't you going to push chapter 1? If you would go ahead and push chapter 1 to this, then I can get started with merging your book. Thank you so much!!! Steve

**Comment by jimcat8** [comment]
> @jimcat8 Don't do the .pages files. That's something that is required of editors. Also, did you mean to only submit the .pages file and then 3 .jpgs and that's it? Weren't you going to push chapter 1? If you would go ahead and push chapter 1 to this, then I can get started with merging your book. Also, the editors will always take care of getting your submissions to the correct directory when they are new. Thank you so much!!!

Isn't it agreed that a file corresponds to a PR?I first make a PR of the folder and pictures,After passing,I will fetch and merge, one file and one pr

**Comment by jimcat8** [comment]
> @jimcat8 Don't do the .pages files. That's something that is required of editors. Also, did you mean to only submit the .pages file and then 3 .jpgs and that's it? Weren't you going to push chapter 1? If you would go ahead and push chapter 1 to this, then I can get started with merging your book. Also, the editors will always take care of getting your submissions to the correct directory when they are new. Thank you so much!!!

Other authors' "books" have .pages files, is this automatic? Or was it created manually?

**Comment by sspencerwire** [comment]
> Other authors' "books" have .pages files, is this automatic? Or was it created manually?

@jimcat8 Just a little more information:

* the .pages file will be created, but that is the job of the editor. It's not a contributor process. You are very observant and I get that! It's appreciated, but in this case, the editor will create the .pages file. The same goes for the folder within the books section. They need to look at the big picture and decide on the folder name. It has no bearing on the content that you are creating! If you want me to act on this PR I will. I'm just saying there's no need to do it, as it is the editor's job to create the .pages file and decide on the directory structure.

**Comment by sspencerwire** [comment]
> Isn't it agreed that a file corresponds to a PR?I first make a PR of the folder and pictures,After passing,I will fetch and merge, one file and one pr. 

Again, (see below) but the .pages and folder are the responsibility of the editor. All you needed to do is push your images, which you could have included with your first chapter if you wanted, which is why I asked you about it.

**Comment by sspencerwire** [comment]
I'll go ahead an pull this into an editing branch and just make sure everything looks OK. Just take the notes for future reference. No need to work so hard! ;-) The editors will do the configuration and filesystem foo. Thank you again for the contribution and I'll look forward to the chapters.

**Pull request merged**
