### PR TITLE
add 8.5.it.md

### PR DESCRIPTION
**Pull request by ambaradan**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [x] Is this a non-English contribution? 
- [x] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@ambaradan We have a hold on these for the moment. (the 8.4, 8.5, translation files specifically). We have an issue that we need to resolve that makes these files not show up correctly in the listing. The problem is because of the "." in the filename. Unfortunately, we are linking to the filenames in many locations now, so changing the "." to an "_" isn't going to be easy to do. Anyway, please stand by on this one. I appreciate your continued good work!

**Comment by sspencerwire** [comment]
@ambaradan I just realized that this post has a translation for migrate2rocky as well. It is better to make a new PR for a new document. Here's why: As I've stated earlier, the 8.5.it.md document translation is currently on hold because of an issue with the file names that we need to work through. Having migrate2rocky.it.md included in this PR, means that first, I missed it, and second, we have to pull the PR, remove the 8.5.it.md translation, and then check and merge the migrate2rocky.it.md. Keeping the documents separate, means we only need to worry about one document. (also, I won't miss it!!!). Thanks again for continuing your translation work. I'm hoping that you have a copy of the 8.5.it.md translation, as that is going to be deleted from this PR so that I can merge your migrate2rocky.it.md translation. If not, I'll preserve it in a folder on my machine.

**Comment by ambaradan** [comment]
Of course I have a copy of 8.5.it.md, the problem is that I do not understand how to make separate push requests, if I make a new push request from the GitHub Web GUI it puts it in the queue to what is not yet merged, I will have to try how to do it with code (editor).

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il martedì 30 novembre 2021 15:01, sspencerwire ***@***.***> ha scritto:

**Comment by ambaradan** [comment]
I encountered a problem, the page migrate2rocky.it.md is in the right position but if I try to select the Italian language in the documentation the page is still in english! The installation page is correctly translated into Italian.

**Comment by sspencerwire** [comment]
> I encountered a problem, the page migrate2rocky.it.md is in the right position but if I try to select the Italian language in the documentation the page is still in english! The installation page is correctly translated into Italian.

Let me take a look...

**Comment by sspencerwire** [comment]
> Let me take a look...

I have a local copy of the mkdocs server on my workstation which allows me to check things before pushing them live. This is all working as you would expect and I can see your Italian translation of the migrate2rocky.it.md when I choose Italian from the languages on the menu. However, I do not see this on the live server. There was another change pushed this morning for the 8-changelog.md document and that isn't showing up either. 

The problem isn't with anything you did and appears to be on the server side of things. I've reported this and am waiting for a response.

**Comment by sspencerwire** [comment]
> Of course I have a copy of 8.5.it.md, the problem is that I do not understand how to make separate push requests, if I make a new push request from the GitHub Web GUI it puts it in the queue to what is not yet merged, I will have to try how to do it with code (editor).

Once you have a new document in your fork of the documentation, you should be able to simply click on "Pull Requests" and then "New Pull Request" and I believe it will give you a way to select the document that you want to do a new PR for. (I don't do things this way personally, I have a local copy of the repository and do git commits and PR's from that to my local fork). Anyway, give that a try next time you want to do a new document and you should be OK.  If not, I'll test it on my end.

**Comment by ambaradan** [comment]
Thanks, for the next translation I will definitely try to do as suggested. I also work on a copy of the repository but only did PR from the Web GUI. It's time to study git better, but time is always short!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il martedì 30 novembre 2021 21:18, sspencerwire ***@***.***> ha scritto:

**Comment by sspencerwire** [comment]
We found the issue with an upstream package (one of the plugins that we use for the documentation site) that was auto-updated and then promptly broke the build system. A PR was pushed to correct the issue to the upstream and it was merged, but now we have to wait for them to release a fix or roll back to a previous version. That's still up in the air at the moment. Just wanted to keep you in the loop and reinforce that this was not caused by the merge of your translation, and in fact is a wider issue that you helped us find!  Thank you!

**Comment by sspencerwire** [comment]
@ambaradan OK, a temporary fix is in place. I can verify that the English changes that were made are now showing up. Hopefully you can see your migrate2rocky.it.md file now?  Let me know if there is still an issue.

**Comment by ambaradan** [comment]
Great, it works perfectly, right now I started with ansible. Good job

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il mercoledì 1 dicembre 2021 17:18, sspencerwire ***@***.***> ha scritto:

**Pull request merged**
