### PR TITLE
docs: add BreakingPitt as a contributor for content and translation

### PR DESCRIPTION
**Pull request by BreakingPitt**
Added BreakingPitt as a contributor for content and translation.

### CODE REVIEW

**Comment by sspencerwire** [comment]
Good day @BreakingPitt ! I can't merge this, unfortunately. These changes need to be made by the all-contributors bot and making modifications to the content manually is unsupported. Can you tell me what contributions to content you've made? I know you have contributed to translations, and I'll definitely add you for that. When we talk about "content" we are talking about the source, or English, files. If you've made a change to these source files, let me know what that is. Thank you for all you are doing with the translation team!!!

**Comment by BreakingPitt** [comment]
Hi @sspencerwire:

Oh.. I thought that it was a manual job, it doesn't matter I will close the pull requests. 

About the content, I have an article that I'll try to upload as soon as possible(today if possible) about installing Hashicorp Packer on Rocky Linux to complement the existing article in the documentation on packer and vmware.

If you were so kind to add me as translator it would be great.

Thanks!

**Comment by sspencerwire** [comment]
@all-contributors please add @BreakingPitt for translation

**Comment by sspencerwire** [comment]
@BreakingPitt Done! Just have to wait for mkdocs to rebuild and it will show up. Thanks again and I'll watch for the new document!

**Pull request closed without merging**
