### PR TITLE
installation.zh.md

### PR DESCRIPTION
**Pull request by dengwenbin**
New Create and translations  installation.zh.md (Chinese Simplified)

#### Author checklist (Completed by original Author)
- [x] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [x] Is this a non-English contribution? 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Check that document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Basic Editorial Review)
- [x] 4th Pass (Detailed Editorial Review and Peer Review)
- [x] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@dengwenbin All translations must be done through our Crowdin interface. I'm notifying @alemorvan to help you get set up there.

**Comment by dengwenbin** [comment]
> @dengwenbin All translations must be done through our Crowdin interface. I'm notifying @alemorvan to help you get set up there and thank you for your interest in Rocky Linux and translations!

OK I just joined The Crowdin's Project rockylinuxorg with github account.
It's late now. I have to go to bed and go to work tomorrow. It's 0:27 on August 2, Beijing time.

**Comment by sspencerwire** [comment]
Must be done through Crowdin... closing PR. Thank you @dengwenbin

**Comment by sspencerwire** [comment]
@all-contributors add @dengwenbin for translation

**Comment by sspencerwire** [comment]
@all-contributors please add @dengwenbin for translations.

**Pull request closed without merging**
