### PR TITLE
Add index translated for pt_BR

### PR DESCRIPTION
**Pull request by Bakrog**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [x] Is this a non-English contribution? 
- [x] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@Bakrog Thanks for your translation!  Unfortunately, the back-end server is not quite ready for it yet. Also, I know you were told that you would probably need the pt_BR extension, but it looks like the only extension you will need is "pt"... that can be fixed when the file is edited and merged, so you don't need to worry about that.  Thanks again!

**Comment by Bakrog** [comment]
> @Bakrog Thanks for your translation! Unfortunately, the back-end server is not quite ready for it yet. Also, I know you were told that you would probably need the pt_BR extension, but it looks like the only extension you will need is "pt"... that can be fixed when the file is edited and merged, so you don't need to worry about that. Thanks again!

Hello, I did change the file name and some more additional things in the transaltion.

**Comment by justasojourner** [comment]
Hi @Bakrog - quick update for you.

As @sspencerwire mentioned, on my further research for the modules languages support I found that they cannot accept locale codes for variants of languages (pt_BR nor en_GB / en_US / en_AU / zh_CN etc.)

Soon we will be updating the overall directory structure of the documentation website and the documentation files and folders will move from [root]/docs to [root]. So your file will need to change from docs/index.pt.md to index.pt.md.

The overall directory structure change will also mean that everyone will have to pull down the changes from documentation/main to their GitHub fork and from there to their local clone on their computer. You will then need to update your PR.

**_Do not do anything yet_** - we will advise everyone when the repository change has been done. Also I **_strongly recommend_** that you make a backup copy of your document outside of your local repository as a safety measure.

**Comment by sspencerwire** [comment]
Hi @Bakrog , the big changes that we were hoping to make to the documentation did not come about, and it doesn't look like that will happen anytime soon. I've reviewed your PR and there is only one issue that I can see. If you can push through a fix for this, I'll go ahead and merge your PR (the Portuguese language _HAS_ been added, so we are ready for this document now): 

The issue: Admonitions must appear as English, but you can add a title to them in your language: In the case of this translation, this would be done by doing the following: 

!!! Note "Nota"
    Nem todas as funcionalidades estarão disponíveis em todos os idiomas, isto é uma limitação dos módulos do MkDocs disponíveis.

If you would push through this one fix, I'll go ahead and merge this document, and thanks again for your translation!

**Pull request merged**
