### PR TITLE
Writing pam documentation

### PR DESCRIPTION
**Pull request by alemorvan**
#### Author checklist (Completed by original Author)
- [x] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [x] Is this a non-English contribution? 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by alemorvan** [comment]
As request by @jimcat8, we need a PAM documentation.

Here is the translation of my initial PAM doc (for centos 7).

Please consider making the tests needed to validate the good functionnement of the modules (does they still exist?).

Hope this doc will help you @jimcat8 

Thx @sspencerwire for the review

**Comment by EzequielBruni** [comment]
Adding this to my to-do list.

**Comment by sspencerwire** [comment]
> Adding this to my to-do list.

As you are planning on doing the editing on the @EzequielBruni , I'm just going to run it through some testing on both 8.6 and 9.0. It _should_ work the same way as here, but since it was written for CentOS 7, it's probably a good idea to test it. Don't let it hold up your edit and merge, however. I can always push any changes or notes needed after testing. Thank you, and welcome back!!

**Comment by sspencerwire** [comment]
> > Adding this to my to-do list.
> 
> As you are planning on doing the editing on this @EzequielBruni, I'm just going to run it through some testing on both 8.6 and 9.0. It _should_ work the same way as here, but since it was written for CentOS 7, it's probably a good idea to test it. Don't let it hold up your edit and merge, however. I can always push any changes or notes needed after testing. Thank you, and welcome back!!

Instead of testing, I checked out release notes associated with upstream between 7 and 8 and 8 and 9, and the only item that I found that is different, isn't mentioned in @alemorvan 's document, so you can edit and merge when ready. Thank you!!

**Comment by EzequielBruni** [comment]
@sspencerwire I made a few significant edits, and for some reason I was forced to make a new branch. If you wouldn't mind double checking my work, I'd appreciate it.

https://github.com/rocky-linux/documentation/blob/pr/746/docs/guides/security/pam.md

**Comment by sspencerwire** [comment]
> @sspencerwire I made a few significant edits, and for some reason I was forced to make a new branch. If you wouldn't mind double checking my work, I'd appreciate it.
> 
> https://github.com/rocky-linux/documentation/blob/pr/746/docs/guides/security/pam.md

I'm on it! Thank you!

**Pull request merged**
