### PR TITLE
SSH CA Key Signing

### PR DESCRIPTION
**Pull request by hs303**
Hello,
this is my first contribution to the documentation. I hope it meets your requirements.
Thank you for maintaining the project.

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@hs303 This is very good! Here's a couple of things to help make it slightly better. (I can always do this on the final edit if you don't want to): 
1. When using the title meta, markdown linters see this as the Level 1 heading for the document, so there is no need to place a level 1 heading inside the content, linters sees this as an error. 

2. You've used "Prerequisite" and "Skills" here and have identical content under them. I'd stick to "Prerequisites" (personal preference). Consider adding something along the lines of "skill managing content from the command line" and "previous experience with SSH key generation helpful, but not required." and bullet those items. Ask yourself the question: What would someone who has never done this before need to know?

3. A conclusion is a great way to end your document. A simple concluding statement or paragraph is sufficient.

Again, this looks very good and is definitely a good candidate for Rocky Linux documentation. Thank you @hs303 !!

**Comment by hs303** [comment]
@sspencerwire I have tried to address all of your suggestions. Feel free to make some adjustments, if you'd like to. I also decided to add a few words about the key revocation process.

**Review by sspencerwire — APPROVED** [review]
Nice! Thank you again @hs303 !

**Comment by sspencerwire** [comment]
@all-contributors add @hs303 for content

**Pull request merged**
