### PR TITLE
Wip kvm

### PR DESCRIPTION
**Pull request by NezSez**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [ ] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by NezSez** [comment]
This a draft of a doc I started more than a year ago. It's currently **VERY** disorganized and has almost no markdown set yet. Feel free to fix'er up, but note that I'm still working on it and if you move things around too much I might get confused as I put somethings in a position where it was relevant in context, even if that isn't apparent at the current state.

**Comment by sspencerwire** [comment]
> This a draft of a doc I started more than a year ago. It's currently **VERY** disorganized and has almost no markdown set yet. Feel free to fix'er up, but note that I'm still working on it and if you move things around too much I might get confused as I put somethings in a position where it was relevant in context, even if that isn't apparent at the current state.

Glad to see you are working on a couple of projects! I realize this is a WIP at this point, but take care to clean up those links when you get to that point (the ones that are failing in the URL checker). I'm sure you will! The one can probably be fixed by by finding the released version (rather than the beta (...9-beta below):

 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html/configuring_and_managing_virtualization/proc_enabling-virtualization-in-rhel-9_configuring-and-managing-virtualization,failed,guides/virtualization/kvm.md

 https://www.kernel.org/doc/html/latest/x86/intel-iommu.html,failed,guides/virtualization/kvm.md

**Review by NezSez — COMMENTED** [review]
Just merged main into existing branch

**Comment by NezSez** [comment]
The moving target of sources and citations is a never ending ordeal.

**Pull request closed without merging**
