### PR TITLE
Add installation guide for Terminator

### PR DESCRIPTION
**Pull request by andcscott**
Related to #2417 

This doc provides installation instructions for Terminator on Rocky Linux 9.4. Please advise if any updates are required, thanks!

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by Grammaresque** [comment]
Addresses Issue #2417

**Comment by sspencerwire** [comment]
Thanks very much @andcscott! It turns out that I use terminator all the time, so depending on what I see when editing, I may add to it. I mean, basically, I just use it. ;-)

**Review by sspencerwire — APPROVED** [review]

**Comment by sspencerwire** [comment]
@all-contributors add @andcscott as a contributor

**Comment by sspencerwire** [comment]
@all-contributors add @andcscott as contributor

**Comment by sspencerwire** [comment]
@all-contributors add @andcscott for content

**Comment by andcscott** [comment]
@sspencerwire Same here! And I _always_ forget that it's in ELPA when installing a new machine!! In any case, thank you for reviewing so quickly.

**Pull request merged**
