### PR TITLE
Monitoring Rocky Linux nodes or clusters by Ganglia

### PR DESCRIPTION
**Pull request by berlin2123**
## Author checklist (to be completed by original Author)
- [*] Is this document a good fit for the Rocky project ?
- [*] Is this a non-English contribution? 
- [*] Title and Author MetaTags have been inserted into the document 
- [*] If applicable, steps and instructions have been tested to work on a real system
- [*] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@berlin2123 Thank you so much for your contribution! I'm not going to have time to work this PR until probably Monday. I'm a little concerned by the PHP 5.6 requirement, but you seem to have dealt with that in the notes about a Docker container. Anyway, I will try to get to this on Monday! Thanks again! Steve

**Comment by sspencerwire** [comment]
Good day @berlin2123. Just a few things to note:
1. Can I have your first and last name for the author meta? If not, we can continue to use your Github handle
2. Regarding the PHP issue, have you seen and/or tried this: http://csic.som.emory.edu/~lzhou/blogs/?p=654
3. Last, I'm going to need to lab test this a little while running this document so this may take a little longer. Hope you are OK with that!

Thanks again for your contribution!!

**Comment by berlin2123** [comment]
Good day @sspencerwire,
1. Github handle is ok.
2. the files in ganglia-web-3.7.5 is diff with the case that leizhou posted.
3. I re-tested this document in a freshly installed Rocky linux 8.4 system, last night. All goes will, except “maybe need ‘dnf update’ in the RL8.4 host machine”. I go thoungh all of my document without update the freshly RL8.4 firstly, however can not access the web interface. And then, just after dnf update and reboot of the RL8.4 host machine, and without any more did,  the web interface then works fine.
4. ganglia-web seems hardly maintained now:  https://github.com/ganglia/ganglia-web/tags

**Comment by berlin2123** [comment]
In fact, just like that [RocksCluster has always chosen ganglia](http://www.rocksclusters.org/downloads/2017-12-01-download-rocks-7-0-manzanita.html), ganglia has always been a good choice for monitoring self-built HPC cluster.
Nowadays, more and more clusters are directly purchased as a whole, which has included supplier’s proprietary monitoring software. Self-built clusters are becoming fewer and fewer.The relatively reduced number of users may be one of the important reasons why Ganglia is not active enough to update.
Putting this into the RockyLinux documentation can attract more users and programmers' attention, which will help the active update of Ganglia.

**Comment by wsoyinka** [comment]
@berlin2123   - You are absolutely correct !!  
We would like for you to test and add a little RockyLinux-ness to the existing documentation that you are proposing.
Thanks :-).

**Pull request closed without merging**
