### PR TITLE
add new file

### PR DESCRIPTION
**Pull request by jimcat8**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by alemorvan** [comment]
@jimcat8 there is nothing to say about this chapter. It will be a very great one. It will complete the grep part of the admin book with a lot more complex things.

Congrats jimcat8, I know it is not easy to write that sort of chapter from scratch!
It's a very good idea!

**Review by alemorvan — DISMISSED** [review]

**Comment by alemorvan** [comment]
I've just added my approval. This is an excellent chapter, rich in information.
It belongs in the administrator's guide (or one day even in an advanced administrator's guide).
Well done Jimcat.

The only comment I have concerns the title (that's saying something). It's a cool title for a blog, but I think it clashes with the titles of the other chapters in the guide.

Maybe a better title: "Deep dive into grep, sed and awk - the three Swordsmen".

@sspencerwire could we merge this PR if @jimcat8 is ready (it's actually in draft mode) and has change the title?

**Comment by sspencerwire** [comment]
> I've just added my approval. This is an excellent chapter, rich in information. It belongs in the administrator's guide (or one day even in an advanced administrator's guide). Well done Jimcat.
> 
> The only comment I have concerns the title (that's saying something). It's a cool title for a blog, but I think it clashes with the titles of the other chapters in the guide.
> 
> Maybe a better title: "Deep dive into grep, sed and awk - the three Swordsmen".
> 
> @sspencerwire could we merge this PR if @jimcat8 is ready (it's actually in draft mode) and has change the title?

I'm ready to merge the PR as soon as @jimcat8 takes it out of draft mode. It may require some light editing after merging, but it doesn't look like it will take much.

**Review by sspencerwire — APPROVED** [review]
@jimcat8 It looks good. There may be some light editing needed, but I'm inclined to merge this and let Anna take a look if she has time today, or I'll run through it tomorrow.

**Pull request merged**
