### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by garthus1**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [x] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by calderds** [comment]
Looks good! Leave a comment when you're ready to merge. :)

**Comment by sspencerwire** [comment]
@garthus1 Thanks for the submission Gerald. It mostly looks good, however I do not believe that the EPEL is enabled with the default install of "Minimal" and "Standard" and think that it must be enabled with `dnf install epel-release` followed by a `dnf update`. Can you lab test that particular portion and make sure that your step is correct? Thanks very much!

**Comment by garthus1** [comment]
Spencer, you are correct, should I resubmit or do you want to just add it.
I will remember next time. I want to do all the pieces of a LAMP
installation and then put together for a complete installation. I gues that
can be done through the T.O.C.

Best Wishes,

Gerry
Gerard Arthus
409 Lowell Avenue East
Mishawaka, Indiana
United States
46545
Cell - 574-302-7731
Home - 574-520-1337 <574-217-8726>

Instructor ITT-Tech - Mathematics, Electrical Engineering, and Computer
Engineering.

***@***.***
Notary The State of Indiana #685426
http://www.OpenEducation.org
http://openeducation.org/moodle/  (For Course Portal) Log In as Guest
http://www.linkedin.com/profile/edit?trk=tab_pro
http://www.facebook.com/gerard.arthus
https://archive.org/details/arthusgerardphilosophicalwritings (Philosophical
Discussions)
https://archive.org/details/arthusgerardpoems (Poems)
https://archive.org/details/arthusgerardzoe?sort=titleSorter (Zoe Book)
***@***.***&tab=collections (Gerard Arthus
Collections Page)
https://archive.org/details/arthusgerardhack
<https://archive.org/search.php?query=hacking%20the%20world%20garthus>
(Hacking The World)
https://archive.org/details/arthusgerardmedical&tab=about
(Medical Records)
https://archive.org/details/arthusgerardrec&tab=collection
(Musical Recordings)

https://archive.org/details/arthusgerardpackagingandinstructionmanuals
(Packaging
Collection)
***@***.***&tab=uploads  (All Items Uploaded to
Date)
https://archive.org/details/What_Have_We_Wrought_ (Selected Poem)
https://archive.org/details/A_World_Where_We_Consume_Our_Hearts_ (Selected
Poem)
https://archive.org/details/Here_There_Is_No_Lesson_To_Be_Learned_ (Selected
Poem)
https://archive.org/details/Deception_And_The_Self_Created_Terrorist_Threat_American_Complicity_In_World_W
(Selected
Poem)
https://archive.org/details/Solitary_Horsemen_Reflections_On_Life_In_Cyberspace
(Selected
Poem)

**Comment by sspencerwire** [comment]
@garthus1 I'll create an editing branch and pull it down and make the changes. There is a current PR to update the table of contents document, so I'll hold on adding this until after that's been reviewed, deleted, or merged. It will still show up in the "Guides" when merged however. Thanks!

**Comment by garthus1** [comment]
Spencer,
The corrections all look good to me. Maybe 'Installation of' should be
added to the title. Make sure that they make a LAMP/LEMP installation
category in the TOC; also if you did not notice the mod_ssl was done for
and
unsigned Certificate. I thought that another would be done for the signed
or paid certificate. Just thought that it would be easier to understand in
two steps.

Best wishes,

gerry



Gerard Arthus
409 Lowell Avenue East
Mishawaka, Indiana
United States
46545
Cell - 574-302-7731
Home - 574-520-1337 <574-217-8726>

Instructor ITT-Tech - Mathematics, Electrical Engineering, and Computer
Engineering.

***@***.***
Notary The State of Indiana #685426
http://www.OpenEducation.org
http://openeducation.org/moodle/  (For Course Portal) Log In as Guest
http://www.linkedin.com/profile/edit?trk=tab_pro
http://www.facebook.com/gerard.arthus
https://archive.org/details/arthusgerardphilosophicalwritings (Philosophical
Discussions)
https://archive.org/details/arthusgerardpoems (Poems)
https://archive.org/details/arthusgerardzoe?sort=titleSorter (Zoe Book)
***@***.***&tab=collections (Gerard Arthus
Collections Page)
https://archive.org/details/arthusgerardhack
<https://archive.org/search.php?query=hacking%20the%20world%20garthus>
(Hacking The World)
https://archive.org/details/arthusgerardmedical&tab=about
(Medical Records)
https://archive.org/details/arthusgerardrec&tab=collection
(Musical Recordings)

https://archive.org/details/arthusgerardpackagingandinstructionmanuals
(Packaging
Collection)
***@***.***&tab=uploads  (All Items Uploaded to
Date)
https://archive.org/details/What_Have_We_Wrought_ (Selected Poem)
https://archive.org/details/A_World_Where_We_Consume_Our_Hearts_ (Selected
Poem)
https://archive.org/details/Here_There_Is_No_Lesson_To_Be_Learned_ (Selected
Poem)
https://archive.org/details/Deception_And_The_Self_Created_Terrorist_Threat_American_Complicity_In_World_W
(Selected
Poem)
https://archive.org/details/Solitary_Horsemen_Reflections_On_Life_In_Cyberspace
(Selected
Poem)

**Comment by sspencerwire** [comment]
@garthus1 Gerald, I'll tell you what, if you want to add the "Installation of" we can do that in a new PR, or you can just ask me to do it separately. You may change your mind, however, once you see how long it currently is in the listing in "Guides." If you still want that to be added after you see how it looks currently, it's a simple fix.  Thanks!

**Pull request merged**
