### PR TITLE
docs: Basic punctuation corrections

### PR DESCRIPTION
**Pull request by yashpandey06**
#### Author checklist (Completed by original Author)
- [ ] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ ] If applicable, steps and instructions have been tested to work
- [ ] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by yashpandey06** [comment]
@sspencerwire  let me know if it's incorrect I will close this pr and raise another one

**Comment by sspencerwire** [comment]
> @sspencerwire let me know if it's incorrect I will close this pr and raise another one

Actually, material-mkdocs (what we use) makes no distinction for drawing a line. Markdown appears to accept it as either "***" or "---" as you have changed it. I can't find the most accepted method, but they both work today. @yashpandey06 Do you use a local copy of documentation so that you can see how your changes affect the web rendering? I'm referring to [one of these options](https://docs.rockylinux.org/guides/contribute/localdocs/). It's not required, however it does help me to know that the changes you've proposed here actually render correctly. Let me know either way. I can always revert some changes if it turns out to have broken something.

**Comment by yashpandey06** [comment]
@sspencerwire I don't see it to be broken , so its working ....any what's your point on it !, should I close the pr  do it accordingly?

**Comment by sspencerwire** [comment]
> @sspencerwire I don't see it to be broken , so its working ....any what's your point on it !, should I close the pr do it accordingly?

No, not yet. Let's see if @alemorvan comments back, if you are OK with waiting just a bit.

**Comment by yashpandey06** [comment]
> > @sspencerwire I don't see it to be broken , so its working ....any what's your point on it !, should I close the pr do it accordingly?
> 
> No, not yet. Let's see if @alemorvan comments back, if you are OK with waiting just a bit.

Sure 😄

**Comment by sspencerwire** [comment]
> Hey, thank you for your work @yashpandey06 ... @alemorvan would you mind taking a look at this? I know that he is correct that, while originally using either "_" or "-" for bulleted items, that the current accepted method is "-" I think the replacement of the "_***" with three dashes is incorrect however. Looks like a lot of the changes are OK. Let me know what you think.

Actually, @yashpandey06, I was traveling before and could not check. Unordered lists are preferred to be * not -, so I misspoke above. Do you want to edit your PR?  Thanks!

**Comment by sspencerwire** [comment]
> > Hey, thank you for your work @yashpandey06 ... @alemorvan would you mind taking a look at this? I know that he is correct that, while originally using either "_" or "-" for bulleted items, that the current accepted method is "-" I think the replacement of the "_***" with three dashes is incorrect however. Looks like a lot of the changes are OK. Let me know what you think.
> 
> Actually, @yashpandey06, I was traveling before and could not check. Unordered lists are preferred to be * not -, so I misspoke above. Do you want to edit your PR? Thanks!

OK, ignore my last (above): The problem I was seeing in the document I was editing was that the unordered list items had "mixed" formatting. The markdownlint requires you to pick one (- or *) and then stick with it throughout. So again, neither is wrong.

**Comment by yashpandey06** [comment]
@sspencerwire got it !

**Review by alemorvan — APPROVED** [review]
Let's see how it looks like

**Pull request merged**
