### PR TITLE
New document and images for running Rocky Linux in VirtualBox

### PR DESCRIPTION
**Pull request by sspencerwire**
* Document requested during go-live of 8.5
* Lab tested and working

## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [x] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@EzequielBruni If you get a chance, take an editing pass on this and merge it if it's OK.  Thanks!

**Comment by EzequielBruni** [comment]
Sure, I'll have a look.

**Comment by tcooper** [comment]
@sspencerwire This is an amazing start.

Comments...

- Where possible (like when you've selected a single option from multiple ones) it might be good to link to the Oracle VirtualBox documentation with a `[more information](<link>)`. For example, while configuring the guest you write "You will get a dialog box for creating various virtual hard disk types. For the sake of this document, just keep the default (VDI):". This could be augmented with "See the Oracle VirtualBox documentation for [more information](https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/vdidetails.html) about selecting virtual hard disk types." 
- You are recommending setting the Video Memory to the maximum possible in the GUI (128MB). It should be emphasized in this section (which may be the issue that precipitated the entire doc) that this setting should be set depending on the purpose of the guest system, and indeed, also depends on the host screen resolution. A link to the Oracle [Display Settings](`https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/settings-display.html`) docs would be useful. Also, the value settable for guests may be higher from the command line (`VBoxManage`) than from the GUI. This could be an _advanced tip_ as it could require a whole other document on using `VBoxManage`.
- A future update could also include adding/updating the VirtualBox Guest Additions inside the guest VM. As of the time of release of Rocky 8.5 the standard Linux Guest Additions would not fully build (there are kernel modules) and install. I had to use the nightly build of the Linux Guest Additions. An update to VirtualBox will likely resolve that but I don't know which version has that fixed.

All of the above can be addressed with a future update of this document. Depending on how polished you want to release it you can either update it later or do it now before deploying to the production web site.

**Comment by EzequielBruni** [comment]
Agh, I was gonna edit now. But @tcooper makes some excellent points. I'll wait 'til you decide what (if anything) to do with them @sspencerwire.

**Comment by tcooper** [comment]
@sspencerwire I will add to my above third comment that the latest release of VirtualBox (and Guest Additions) appears to [explicitly add support](https://www.virtualbox.org/wiki/Changelog-6.1#v28) for the RHEL 8.5 kernel(s) (which included Rocky 8.5). I haven't yet verified but expect to do that this weekend.

Perhaps this document should specifically mention the VirtualBox version and link to the changelog?

**Comment by sspencerwire** [comment]
@tcooper @EzequielBruni I'll plan on pushing some changes to this document based on Trevor's suggestions. Great input, by the way!  Based on my schedule this week, and a couple of problems that have cropped in documentation, it may or may not be this week.

**Comment by sspencerwire** [comment]
@tcooper @EzequielBruni I've finally gotten an opportunity to make some of the suggested changes to this document. One thing that was **not** done is that I've not documented the install of the Guest Additions. The reason is that, a) my host is Ubuntu 20.04 b) my VirtualBox version is: "Version 6.1.26_Ubuntu r145957", and c) when I install the guest additions and reboot, I get a VirtualBox Client kernel error. I'm sure this is what you were alluding to Trevor. I've been going to nuke my desktop and install Rocky Linux, however, I've got a bunch of stuff going on right now both Rocky and non-Rocky related, so "now" is just not the time. I've left out any mention of Guest Additions, but if you want to write up a supplement to this Trevor, I'd be fine merging it into this document. 

What I have done is:  

* added links back to Oracle's official documentation where appropriate as suggested
* added an "Advanced Tip" that points to Oracle's VBoxManage documentation
* added some wording (and link) to help explain the video resolution section as suggested 

I'm preparing to push the update now. Thanks again for your review and let me know if I need to make other changes before @EzequielBruni does an edit and merge. My guess, @EzequielBruni, is that you can edit and merge at this point and that we can add in whatever needs to be added in with another edit.

**Pull request merged**
