### PR TITLE
Update index.md, add links to crowdin

### PR DESCRIPTION
**Pull request by SergeCroise**
- dashboard: https://crowdin.com/project/rockydocs
- activity: https://crowdin.com/project/rockydocs/activity-stream

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by SergeCroise** [comment]
Hello dear translators,
please review.
@gannazhyrnova , @alexiarstein , @grammaresque ,
@antoine , @ShyRain , @ambaradan

**Comment by sspencerwire** [comment]
@SergeCroise I totally agree with having the links there, however I think that they need to be better identified, rather than just fitting them into the original sentence structure. Do you want to take another crack at that??  Other opinions are (of course) welcome.

**Comment by SergeCroise** [comment]
> @SergeCroise I totally agree with having the links there, however I think that they need to be better identified, rather than just fitting them into the original sentence structure. Do you want to take another crack at that?? Other opinions are (of course) welcome.

@wale , @sspencerwire 
the activity-stream link could also appear in the merge commits of crowdin (commit_message: <link>).

**Comment by sspencerwire** [comment]
@SergeCroise I'm basically fine with this. I'm not certain how the activity stream link helps in the meta. We will see if that needs to be removed after. This is a draft at the moment, so if you are ready for it to merge, please convert it to ready for review. ;-)

**Comment by SergeCroise** [comment]
Please feel free to modify or revert my changes

**Comment by sspencerwire** [comment]
I just realized that this was no longer a draft and that it was marked ready to merge. I've got one final question: Have you tested the addition of the link to the meta @SergeCroise ? In other words: Does it work in the web interface (`mkdocs`)... I can test this to be certain, too.

**Comment by SergeCroise** [comment]
Hello 
@sspencerwire , @wsoyinka 
Please feel free to modify or revert my changes.

**Pull request merged**
