### PR TITLE
Text formatting repair

### PR DESCRIPTION
**Pull request by jimcat8**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@jimcat8... The purpose of formatting of the links is to give as much information about the link as possible. You've suggested replacing [upstream link here](link), with simply [here]. This is the recommended action:
"Links, or urls, should tell the user exactly where they'll go if they click on them."  We've attempted to do that w/o actually naming the upstream. @NeilHanlon Would you mind taking a look at the other changes suggested here?

**Comment by jimcat8** [comment]
> @jimcat8... The purpose of formatting of the links is to give as much information about the link as possible. You've suggested replacing [upstream link here](link), with simply [here]. This is the recommended action: "Links, or urls, should tell the user exactly where they'll go if they click on them." We've attempted to do that w/o actually naming the upstream. @NeilHanlon Would you mind taking a look at the other changes suggested here?

Because that's what the previous text looks like.

**Review by sspencerwire — APPROVED** [review]

**Comment by sspencerwire** [comment]
> > @jimcat8... The purpose of formatting of the links is to give as much information about the link as possible. You've suggested replacing [upstream link here](link), with simply [here]. This is the recommended action: "Links, or urls, should tell the user exactly where they'll go if they click on them." We've attempted to do that w/o actually naming the upstream. @NeilHanlon Would you mind taking a look at the other changes suggested here?
> 
> Because that's what the previous text looks like.

Yes, and that is a behavior that we are trying to correct.

**Comment by sspencerwire** [comment]
@jimcat8 I've reverted the link changes in your PR, but the additional information you provided is correct (other than the spelling of "Gallery" which I've fixed.) In a plural, "galleries" would be correct, but in this instance it should be singular. https://learn.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli

**Pull request merged**
