### PR TITLE
Simplified Chinese translation of index.md

### PR DESCRIPTION
**Pull request by yangxuan74**
Simplified Chinese translation of index.md

## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [x] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by calderds** [comment]
Would it be possible for the links to point to the Chinese versions of the documentation pages? Maybe the web team can create soft links if the page hasn't been made yet

**Comment by yangxuan74** [comment]
I didn't experiment whether it can link to the Chinese page. The menu above has language options. Click it first to link to the Chinese page

**Comment by calderds** [comment]
Ok, sounds good. @EzequielBruni good to merge?

**Comment by EzequielBruni** [comment]
Sounds alright to me.

**Pull request merged**
