### PR TITLE
Rl git workflow

### PR DESCRIPTION
**Pull request by sspencerwire**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
Made every effort to check this document before the PR. Will not be available for a few days if there is a problem. Thanks.

**Comment by EzequielBruni** [comment]
This is useful, and I'm going to edit it over the next day or so. I'm wondering if we shouldn't move it to another folder, though.

**Comment by alemorvan** [comment]
Maybe it's a good time to think about how to use the git repos and extend the rights.

Obviously the main branch should be protected, but for contributors like me, this workflow is quite heavy.

I should be able to work directly in branches of the main repos without having to fork it. 

While I don't have the right to create a branch, why not, I should be able to pull or push changes from the main repos directly to my local machine.

This would greatly simplify Steven's reviews of my work.

Don't forget that git is a collaborative workflow!

**Comment by sspencerwire** [comment]
@EzequielBruni I also thought that it should probably be in a different folder, and accessible from the How To Contribute page. Not sure If that would maybe be the spot for it instead. Perhaps a link off of that page. After running through this document, even though it is currently my workflow, I'm thinking that I could actually rewrite parts of this to emphasize the use of Atom and the command line and leave it at that. It would be simpler, and still very functional. If you feel like you want to wait to merge it until A) we find a good spot for it and B) I perhaps push an edit, that would be fine. I'm still out mostly until the end of this week at the earliest.  Thanks!

**Comment by sspencerwire** [comment]
@EzequielBruni I decided to make both Git-Cola and Atom optional elements, rather than re-writing portions of the document for Atom only. That might happen as a separate workflow later. @wsoyinka See Ezequiel's comment about a different folder and my response. What do you think about linking this from the How To Contribute document, rather than having it in guides?  Thanks, Steve

**Comment by EzequielBruni** [comment]
Okay, It's gotten a good preliminary edit (I think). I've merged it with main for now, pending a decisions on where to link it. It's not in the TOC, for obvious reasons...

**Comment by NeilHanlon** [comment]
> Maybe it's a good time to think about how to use the git repos and extend the rights.
> 
> Obviously the main branch should be protected, but for contributors like me, this workflow is quite heavy.
> 
> I should be able to work directly in branches of the main repos without having to fork it. 
> 
> While I don't have the right to create a branch, why not, I should be able to pull or push changes from the main repos directly to my local machine.
> 
> This would greatly simplify Steven's reviews of my work.
> 
> Don't forget that git is a collaborative workflow!

Reviewers can easily check out and view work in your fork using command line tools, or by opening draft pull requests. 

There should be really only two branches on the rockylinux git. develop, and main. work happens on develop, and is squash merged onto main for releases to the main site.

if tooling, infra, advise, etc is needed to help with this process, perhaps some bots or what not, we can certainly investigate that. but giving push access directly to docs.rockylinux.org is a nonstarter.

**Pull request merged**
