### PR TITLE
Fixed som minor typos

### PR DESCRIPTION
**Pull request by danopogac**
Fixed som minor typos

## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [x] 1st Pass (Check that document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Basic Editorial Review)
- [x] 4th Pass (Detailed Editorial Review and Peer Review)
- [x] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by wsoyinka** [comment]
Unable to see the specific changes made to this guide.

**Comment by danopogac** [comment]
Daemon name is lsyncd not lsycnd

**Comment by NeilHanlon** [comment]
@wsoyinka took me a sec but I see it now lol

**Comment by sspencerwire** [comment]
Thanks to @danopogac for bringing this to my attention!  While I always strive for accuracy, I'm **definitely** human and do make mistakes. Merging!

**Pull request merged**
