### PR TITLE
Change the rest of the docs to be alined with the dnf module 

### PR DESCRIPTION
**Pull request by Atroskelis**
Modified the rest of the documentation to align completely to the dnf module change and change any php81 referencences

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@Atroskelis Thank you for your submission. Have you tested this with the LibreNMS procedure?  This document was written some time ago, when RL 8 was the only Rocky Linux available. It was reviewed when 9 came out and some changes made, HOWEVER, the version of PHP at the time on RL 9, was 8.0 and 8.1 was not available. A quick check shows that this is still the case. The REMI repository was used to allow PHP 8.1, the minimum supported for LibreNMS. If you have not tested your changes on this procedure, then I'll need to close this PR. Let me know what you've done!  Thank you again!

**Comment by sspencerwire** [comment]
> @Atroskelis Thank you for your submission. Have you tested this with the LibreNMS procedure? This document was written some time ago, when RL 8 was the only Rocky Linux available. It was reviewed when 9 came out and some changes made, HOWEVER, the version of PHP at the time on RL 9, was 8.0 and 8.1 was not available. A quick check shows that this is still the case. The REMI repository was used to allow PHP 8.1, the minimum supported for LibreNMS. If you have not tested your changes on this procedure, then I'll need to close this PR. Let me know what you've done! Thank you again!
> 
> For more information, refer to https://docs.librenms.org/Installation/Install-LibreNMS/
It does appear (in RL 9) that PHP 8.1 is available as a module stream. The official documentation (the link shared above) has not been updated in some time, so it is possible that-with RL 9 at least-your changes would be OK.  Provided you've tested them in the procedure, but you would still need to enable the module, which I don't see in your PR changes.

**Comment by Atroskelis** [comment]
@sspencerwire  The documentation was fixed with the official librenms documentation as a reference.

But the initial interest came today when i had a fresh Rocky 9 and wanted to install librenms and stumbled upon the broken rocky documenation, as half of it was using the dnf module thus replacing the command php81 with php and half was not. Thus the changes made.

From what i could guess it does seem that the Rocky9 Appsteam has php 8.1 and php 8.2. 
image

Alas, it would still require fixing the documentation, and with this PR it makes it functional.

If you desire, the next time i change it, it will feature the native appstream package.

**Comment by sspencerwire** [comment]
> Hello,
> 
> I shall try to explain
> 
> At the moment the Rocky librenms install docs uses the dnf to replace the default php install with the remi install. Initially the whole documentation used the php81 module which replaces all paths/executables/etc with php81 instead of php.
> 
> image
> 
> This means that the remi install will replace all php aspects. Now, half of the documentation uses php paths and half uses php81 paths, hence this PR. If you use the dnf module to install basic php you do not have this path below.

I'm sorry @Atroskelis, I don't see the "half" that uses anything. In fact, all I see is REMI php paths. I do not have an install of this at the moment to verify, so here's what I'm going to do: I'll merge this PR as is. At my earliest convenience, I'll roll a new install of LibreNMS using the changed instructions. *Just these changes that you've put forward.* If I can install step-by-step as an end user would AND the paths for the files are as you say, no harm, then I will concede that you are correct and *something* must have been wrong with my original instructions. I'm getting ready to head out of town for 4 days, and I don't want this sitting here languishing. Thank you again for your efforts! 
> 
> image
> 
> Comparing to the official Librenms Install docs, which has thus:
> 
> image

**Review by sspencerwire — APPROVED** [review]

**Pull request merged**
