### PR TITLE
Cockpit KVM Dashboard: add guide

### PR DESCRIPTION
**Pull request by neelchauhan**
#### Author checklist (Completed by original Author)
- [X] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [X] If applicable, steps and instructions have been tested to work
- [X] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@wsoyinka Can you look this procedure over please? It looks OK to me, I'm just not able to test it until tomorrow.  Thanks!

**Comment by alemorvan** [comment]
Very good guide 👍.

**Comment by sspencerwire** [comment]
@neelchauhan I plan to merge this tomorrow morning (for me) and then will take a look at it from an editor's perspective. Thank you for your contribution!!

**Review by sspencerwire — APPROVED** [review]
Looks great @neelchauhan ! Thank you!

**Pull request merged**
