### PR TITLE
Update 00-toc.md

### PR DESCRIPTION
**Pull request by garthus1**
## Author checklist (to be completed by original Author)
- [ ] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by garthus1** [comment]
Two errors that I picked up but did not no how to change file after it was pushed.

Gerry

**Review by alemorvan — COMMENTED** [review]
Thank you @garthus1

**Comment by alemorvan** [comment]
You did well @garthus1.
We can't merge our work directly with the main branch.
Somebody has to review and merge it for you. As this, each change has a review.

**Comment by garthus1** [comment]
I understand that and they made it better, I did not know whether to use
Yum or dbf and they replaced YUM so I guess my question is answered without
asking. Can I insert images in that Tutorial; I much prefer to have images
and I have them already.

Best wishes,

Gerry

Gerard Arthus
409 Lowell Avenue East
Mishawaka, Indiana
United States
46545
Cell - 574-302-7731
Home - 574-520-1337 <574-217-8726>

Instructor ITT-Tech - Mathematics, Electrical Engineering, and Computer
Engineering.

***@***.***
Notary The State of Indiana #685426
http://www.OpenEducation.org
http://openeducation.org/moodle/  (For Course Portal) Log In as Guest
http://www.linkedin.com/profile/edit?trk=tab_pro
http://www.facebook.com/gerard.arthus
https://archive.org/details/arthusgerardphilosophicalwritings (Philosophical
Discussions)
https://archive.org/details/arthusgerardpoems (Poems)
https://archive.org/details/arthusgerardzoe?sort=titleSorter (Zoe Book)
***@***.***&tab=collections (Gerard Arthus
Collections Page)
https://archive.org/details/arthusgerardhack
<https://archive.org/search.php?query=hacking%20the%20world%20garthus>
(Hacking The World)
https://archive.org/details/arthusgerardmedical&tab=about
(Medical Records)
https://archive.org/details/arthusgerardrec&tab=collection
(Musical Recordings)

https://archive.org/details/arthusgerardpackagingandinstructionmanuals
(Packaging
Collection)
***@***.***&tab=uploads  (All Items Uploaded to
Date)
https://archive.org/details/What_Have_We_Wrought_ (Selected Poem)
https://archive.org/details/A_World_Where_We_Consume_Our_Hearts_ (Selected
Poem)
https://archive.org/details/Here_There_Is_No_Lesson_To_Be_Learned_ (Selected
Poem)
https://archive.org/details/Deception_And_The_Self_Created_Terrorist_Threat_American_Complicity_In_World_W
(Selected
Poem)
https://archive.org/details/Solitary_Horsemen_Reflections_On_Life_In_Cyberspace
(Selected
Poem)

**Comment by alemorvan** [comment]
Yes you can add images, just upload them in the "images" directory at the same level your document is.
You can have a look on the "rocky installation" markdown file to have an example on how to integrate an image.

**Comment by garthus1** [comment]
I will practice on XFCE page.
Gerry

Gerard Arthus
409 Lowell Avenue East
Mishawaka, Indiana
United States
46545
Cell - 574-302-7731
Home - 574-520-1337 <574-217-8726>

Instructor ITT-Tech - Mathematics, Electrical Engineering, and Computer
Engineering.

***@***.***
Notary The State of Indiana #685426
http://www.OpenEducation.org
http://openeducation.org/moodle/  (For Course Portal) Log In as Guest
http://www.linkedin.com/profile/edit?trk=tab_pro
http://www.facebook.com/gerard.arthus
https://archive.org/details/arthusgerardphilosophicalwritings (Philosophical
Discussions)
https://archive.org/details/arthusgerardpoems (Poems)
https://archive.org/details/arthusgerardzoe?sort=titleSorter (Zoe Book)
***@***.***&tab=collections (Gerard Arthus
Collections Page)
https://archive.org/details/arthusgerardhack
<https://archive.org/search.php?query=hacking%20the%20world%20garthus>
(Hacking The World)
https://archive.org/details/arthusgerardmedical&tab=about
(Medical Records)
https://archive.org/details/arthusgerardrec&tab=collection
(Musical Recordings)

https://archive.org/details/arthusgerardpackagingandinstructionmanuals
(Packaging
Collection)
***@***.***&tab=uploads  (All Items Uploaded to
Date)
https://archive.org/details/What_Have_We_Wrought_ (Selected Poem)
https://archive.org/details/A_World_Where_We_Consume_Our_Hearts_ (Selected
Poem)
https://archive.org/details/Here_There_Is_No_Lesson_To_Be_Learned_ (Selected
Poem)
https://archive.org/details/Deception_And_The_Self_Created_Terrorist_Threat_American_Complicity_In_World_W
(Selected
Poem)
https://archive.org/details/Solitary_Horsemen_Reflections_On_Life_In_Cyberspace
(Selected
Poem)

**Comment by calderds** [comment]
Looks good. Let us know when you're ready for a more detailed review before merge.

**Comment by sspencerwire** [comment]
All, I'm going to close this PR. It looks like all of the issues have been addressed and this particular PR has many conflicts that would have to be resolved anyway. If you feel there are still issues to resolve, feel free to issue a new PR. Thanks very much for your contributions!  Steve

**Pull request closed without merging**
