### PR TITLE
Update index.md (escape key)

### PR DESCRIPTION
**Pull request by SergeCroise**
Typo (escape key)

#### Author checklist (Completed by original Author)
- [ ] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [ ] Is this a non-English contribution? 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by SergeCroise** [comment]
i am not sure if **th** is needed

**Comment by sspencerwire** [comment]
@ambaradan Can you review this for @SergeCroise since this is your document? I believe that the **th** is required, is it not?

**Review by ambaradan — APPROVED** [review]

**Review by ambaradan — COMMENTED** [review]
Wait a moment there must be the `th` stands for theme.

**Comment by ambaradan** [comment]
I got a little confused, the `th` has to fit there is short for _themes_. `<escape>+th` equals `Space + th` to open the choice of built-in themes.

**Comment by ambaradan** [comment]
If anything, the mistake is that I wrote _escape_ and instead there should be _leader_.

**Comment by sspencerwire** [comment]
@ambaradan I see you pushed another PR to fix this so @SergeCroise I'm going to close this one so that there is no confusion. Thank you for your efforts here!!

**Pull request closed without merging**
