### PR TITLE
Release Notes updates for outstanding confirmed issues

### PR DESCRIPTION
**Pull request by tcooper**
## Author checklist (to be completed by original Author)
- [yes ] Is this document a good fit for the Rocky project ?
- [no] Is this a non-English contribution? 
- [yes] Title and Author MetaTags have been inserted into the document 
- [na] If applicable, steps and instructions have been tested to work on a real system
- [yes] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Review by sspencerwire — COMMENTED** [review]
This all looks good. Are we allowed to mention the actual upstream though? In other words, by referencing Red Hat are we in violation legally? Just want to be sure before we merge.

**Comment by tcooper** [comment]
It is my understanding that we can mention the other distribution if we do it correctly and include a disclaimer on the page.

I searched the entire documentation repo and found many places other distributions, including the upstream one, were mentioned and no disclaimer on the pages I examined.

I believe there is going to be a disclaimer in the footer though I'm not sure it's a site footer or a page footer that will be added dynamically with the `mkdocs` run.

That being said. This is a hyperlink and the **only** way it can be inserted is how it has been. We are not framing or inlining the upstream content, it's a plain word link so there should be no issue and likely the disclaimer isn't even required but it will not hurt if it is.

The hyperlink is _not required_ but I think it is helpful to make it clear what we consider upstream of Rocky especially since many adopters may come from other distributions.

For confirmation of the ability to include the hyperlink and where/how the disclaimer will be added please double check with Hayden.

**Comment by sspencerwire** [comment]
@tcooper I guess this whole thing is moot at this point, since 8.4 was moved live last night along with another edited version of this document. I kept watching the channels hoping to catch wind of when they were planning to release, but that never happened. :-) Let me know if you want me to just delete this, or if you want to submit a new version for the current release notes.

**Comment by tcooper** [comment]
I'll just delete the PR and talk to Neil about the review process.

**Pull request closed without merging**
