### PR TITLE
Update php.md

### PR DESCRIPTION
**Pull request by j0eybrinkman**
Removed out-dated info. php 8 is now included in the AppStream repo.

#### Author checklist (Completed by original Author)
- [ x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ x] If applicable, steps and instructions have been tested to work
- [ x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@j0eybrinkman You aren't wrong. PHP 8.0 is currently available in Rocky Linux 8.8 as you note. However there is other content here that needs to change too. Thank you for this!  I'll merge and then make the other changes.

**Review by sspencerwire — APPROVED** [review]

**Comment by j0eybrinkman** [comment]
Ok thank you, this is my first commit to a repo other than my own so figured i'd start small!

**Comment by sspencerwire** [comment]
> Ok thank you, this is my first commit to a repo other than my own so figured i'd start small!

I very much appreciate your contribution!!

**Comment by sspencerwire** [comment]
@all-contributors please add @j0eybrinkman for content

**Comment by sspencerwire** [comment]
@all-contributors please add @j0eybrinkman for content

**Pull request merged**
