### PR TITLE
Basic email system: Big overhaul of grammar and formatting

### PR DESCRIPTION
**Pull request by neelchauhan**
#### Author checklist (Completed by original Author)
- [X] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [X] If applicable, steps and instructions have been tested to work
- [X] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Review by wsoyinka — CHANGES_REQUESTED** [review]
@neelchauhan  -  Thank you .  Great suggestions for improvements here 👍 

For clarity and styling reasons  the original author for this guide prefers the `Shell foobar  >` syntax for shell/command prompts .    @jimcat8  - any additional thoughts ?

Please revert those particular changes and this PR will be ready for merging :-) 

e.g. lines  114, 132, 134 etc etc....

**Comment by sspencerwire** [comment]
@neelchauhan I generally agree with all of your corrections here. I've had a problem with this procedure from the beginning though @jimcat8 simply because part of the process is to install MySQL from source. Having a procedure in place that uses third-party software, and is required to complete the procedure is OK. BUT, MariaDB is the Rocky Linux equivalent package and installing this is trivial. On top of that, package updates and dependencies will continue as long as the OS is supported. When we install a package from source (in this case MySQL) and install the dependencies associated with it, what happens when a dependency updates that does not work with the version of MySQL installed?  The answer is that it breaks the procedure. Rewriting this procedure a little more to instead use MariaDB, rather than MySQL means that this document will not cause a problem down the road. It's a suggestion, but a strong one that I think @wsoyinka would agree with.

**Review by sspencerwire — APPROVED** [review]
Thanks @neelchauhan !! We appreciate the work.

**Review by sspencerwire — APPROVED** [review]

**Comment by wsoyinka** [comment]
@jimcat8  -  I notice that there are 3 different IPs  referenced in the original document - [192.168.100.(5-7)]  Was this a minor oversight or are there 3 different systems involved in the procedures ? 

I also notice that @neelchauhan has helpfully tried to standardize on a single IP - 192.168.100.7 for consistency. 

@jimcat8 please review the changes and confirm your approval. Especially the mysql Vs. mariadb changes that we debating.

**Review by wsoyinka — APPROVED** [review]

**Comment by neelchauhan** [comment]
> @jimcat8 - I notice that there are 3 different IPs referenced in the original document - [192.168.100.(5-7)] Was this a minor oversight or are there 3 different systems involved in the procedures ?

Multiple IPs are involved in this tutorial.

**Comment by jimcat8** [comment]
First of all, installing MySQL with source code is for better performance release, and if you want to upgrade or adopt a variant of MySQL, you can export the data directly. 
Secondly, the roles of the three machines are described at the beginning of the document, mainly to show that the e-mail system is made up of different components. 
In a production environment, it is not recommended to put all components on the same machine, which is actually decoupling.
Finally, DBMS usually doesn't change much unless a major version is updated
@wsoyinka @sspencerwire

**Comment by wsoyinka** [comment]
> First of all, installing MySQL with source code is for better performance release, and if you want to upgrade or adopt a variant of MySQL, you can export the data directly. Secondly, the roles of the three machines are described at the beginning of the document, mainly to show that the e-mail system is made up of different components. In a production environment, it is not recommended to put all components on the same machine, which is actually decoupling. Finally, DBMS usually doesn't change much unless a major version is updated @wsoyinka @sspencerwire

@jimcat8   - Very good.  Please review and approve or disapprove these contributions by @neelchauhan  to this doc. Thank you :-)

**Comment by jimcat8** [comment]
> You don't have to use the same method as the author. Installing Mysql from a repository or docker is also possible.

**Comment by wsoyinka** [comment]
> Very good. Please review and approve or disapprove these contributions by @neelchauhan to this doc. Thank you :-)



> > You don't have to use the same method as the author. Installing Mysql from a repository or docker is also possible.

@jimcat8  - Understood!  Would you prefer that installing mysql from source instructions remain as you had it originally ?

**Comment by jimcat8** [comment]
> > Very good. Please review and approve or disapprove these contributions by @neelchauhan to this doc. Thank you :-)
> 
> > > You don't have to use the same method as the author. Installing Mysql from a repository or docker is also possible.
> 
> @jimcat8 - Understood! Would you prefer that installing mysql from source instructions remain as you had it originally ?

yep

**Comment by wsoyinka** [comment]
> > > Very good. Please review and approve or disapprove these contributions by @neelchauhan to this doc. Thank you :-)
> > 
> > 
> > > > You don't have to use the same method as the author. Installing Mysql from a repository or docker is also possible.
> > 
> > 
> > @jimcat8 - Understood! Would you prefer that installing mysql from source instructions remain as you had it originally ?
> 
> yep

@jimcat8  -  Understood and thank you.  I will recommend that @neelchauhan forks this doc present an alternative approach to doing this !

**Comment by jimcat8** [comment]
"03-single-machine-email-system.md"

Example：`postfix + dovecot + bind + MariaDB`

@wsoyinka @neelchauhan

**Pull request merged**
