### PR TITLE
[WIP] The IPA/IdM book

### PR DESCRIPTION
**Pull request by hbjydev**
#### Author checklist (Completed by original Author)
- [x] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [x] Is this a non-English contribution? 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by hbjydev** [comment]
@EzequielBruni should be happy to see this one :)

**Comment by EzequielBruni** [comment]
Yes I am. Will give it a look soon.

**Comment by sspencerwire** [comment]
@hbjydev Somewhere, as you are writing this, put in an introduction that says exactly what FreeIPA is. Doesn't have to be much, a sentence or two will do. Looking good so far!

**Comment by sspencerwire** [comment]
@hbjydev This has been stagnant for a long time. Are you still interesting in finishing it up?  If not, is anyone else who is following this thread willing to continue it?

**Pull request merged**
