### PR TITLE
Command to modify errors

### PR DESCRIPTION
**Pull request by jimcat8**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by alemorvan** [comment]
Sorry @jimcat8 
It's toi early in the admin guide for this example.
We did not introduce at this step the regexp, but only the wildcards.
This example would be beter in the advanced commands. Or as an extended example in supplement to the actual one, not to replace.

**Comment by sspencerwire** [comment]
@jimcat8 I tend to agree with @alemorvan on this. The goal of the admin guide is to gradually step people up in their understanding of commands and syntax. I would suggest that you write either another chapter or a supplemental section to include some more advanced commands that include regexp.

**Comment by jimcat8** [comment]
@sspencerwire @alemorvan I am infected with COVID-19, and now it is the fifth day. I don't have the energy to write another tutorial on regular expressions yet.

**Comment by alemorvan** [comment]
I hope you are OK @jimcat8.
Let's wait you are better to move forward.
Keep safe.

We can imagine something like this :

```
* List `/var` files larger than 1 megabyte but less than 1 gigabyte:
ls -lhR /var | grep \- | grep [1-9]*M

Note that it exists something we call "regexp" that permits more advanced search. The regexp will be coverd in the advanced command chapter, but try to understand if you can this advanced sample:

$ ls -lhR /var/ | grep ^\- | grep -E "[1-9]*\.[0-9]*M" 
```

What do you think about it ?

**Comment by jimcat8** [comment]
> I hope you are OK @jimcat8. Let's wait you are better to move forward. Keep safe.
> 
> We can imagine something like this :
> 
> ```
> * List `/var` files larger than 1 megabyte but less than 1 gigabyte:
> ls -lhR /var | grep \- | grep [1-9]*M
> 
> Note that it exists something we call "regexp" that permits more advanced search. The regexp will be coverd in the advanced command chapter, but try to understand if you can this advanced sample:
> 
> $ ls -lhR /var/ | grep ^\- | grep -E "[1-9]*\.[0-9]*M" 
> ```
> 
> What do you think about it ?

It should be noted that the files filtered by these two commands are different.

**Review by sspencerwire — APPROVED** [review]

**Pull request merged**
