### PR TITLE
Revert "Update php.md"

### PR DESCRIPTION
**Pull request by sspencerwire**
Reverts rocky-linux/documentation#1693
Not correct yet...

### CODE REVIEW

**Comment by sspencerwire** [comment]
@j0eybrinkman Unfortunately, after merging there were a bunch of problems. I needed to revert the PR back to the original. If you still have the your PR in your branch, here's what I'd suggest: Go back and read that formatting document again very carefully. Everything needs to be separated by four (4) spaces as soon as you use the tabbed format (`===9.x`) All of the 9.x and the 8.x content should then be kept together, rather than spread out throughout the document. The spacing issues caused the rest of the document to render incorrectly as well. It's a little tricky to do some of this, I'll admit. I (and a few other editors and contributors) use a local copy of the mkdocs web engine so that we can easily "see" how are changes will reflect in the browser, and this helps to keep us from making mistakes. If I had more time today, I'd have gone through your changes and edited them so that they wold work in the document, but I just didn't have the time. Are you on our Mattermost discussion? (chat.rockylinux.org)? If so, I can talk you through some of this. Let me know.  Again, I **do** appreciate your effort!

**Comment by j0eybrinkman** [comment]
@sspencerwire Thank you for letting me know! I will take another go at this later today. And no I am not in the matter most discussion but will join it later today. Again, thank you for the help!

**Comment by sspencerwire** [comment]
@j0eybrinkman Just checking in with you. I didn't want to discourage your contribution to the project. Again, if you join the chat.rockylinux.org platform, I can help you a lot more with what you are attempting to do. No pressure! :-)

**Comment by j0eybrinkman** [comment]
Hi @sspencerwire, you definitely have not discouraged me, quite the opposite. I appreciate your help and detailed responses. I joined the mattermost discussion this morning and  going to follow your advice and take another crack at this!

**Pull request merged**
