### PR TITLE
Update php.md

### PR DESCRIPTION
**Pull request by j0eybrinkman**
Updated and tested for Rocky 9.3

Added $ to bash commands missing it for consistency.

#### Author checklist (Completed by original Author)
- [x ] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ x] If applicable, steps and instructions have been tested to work
- [ x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by alemorvan** [comment]
Good job @j0eybrinkman 
About the missing $:
The markdown linter ask us :
- no $ when thé command print nothing
- add a $ when the command return a value

So please you can remove the $ you added

Thank you for this necessary update

**Comment by sspencerwire** [comment]
> Good job @j0eybrinkman About the missing $: The markdown linter ask us :
> 
> * no $ when thé command print nothing
> * add a $ when the command return a value
> 
> So please you can remove the $ you added
> 
> Thank you for this necessary update

@j0eybrinkman I was just going to echo what @alemorvan put in here too. Here's the deal: If you are a user who is going through the procedure to do the install on your machine, then you probably would be using the copy and paste method for these commands. If you have the $ there, what happens is that is copied also unless you also exclude the prompt. (see https://docs.rockylinux.org/guides/contribute/rockydocs_formatting/#suppressing-the-displayed-prompt-and-automatic-line-feed)

Unfortunately, for your PR there is more. Rather than removing the 8.x content (as you've done) you should probably add sections for installing with 9.x. This can be done using [this routine]( https://docs.rockylinux.org/guides/contribute/rockydocs_formatting/#tabbed-content-within-a-document) always making the latest version (9.x) the first tab.

Can you perhaps take another stab at this? I appreciate your efforts and contributions!

**Comment by j0eybrinkman** [comment]
Hello thank you for the advice. After reading the formatting guide I made some new changes as well as returned the Rocky 8.9 instructions - using the markdown you provided.

**Comment by sspencerwire** [comment]
ALMOST there. :-) The "````markdown" tag (and the 4 ending back tics) is not needed and will not yield the correct results. I've removed those. The other change I made, is to combine the enable and start together. For example:
```
systemctl enable --now httpd
```
That is just to make the document a little more concise. I'll merge this now and take a look at it to make sure it renders OK. Thank you @j0eybrinkman !

**Review by sspencerwire — APPROVED** [review]

**Comment by j0eybrinkman** [comment]
@sspencerwire Thank you for the help, I will spend some more time reading the formatting docs and to try and avoid these mistakes in the future!! @alemorvan Thanks for creating this article I have really enjoyed it.

**Comment by alemorvan** [comment]
@j0eybrinkman look at the php-fpm page
My prefered, more technical

Please note we have as project to make a lemp/lamp book

**Pull request merged**
