### PR TITLE
add translation of rockydocs_web_dev

### PR DESCRIPTION
**Pull request by ambaradan**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [x] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by ambaradan** [comment]
Hello, I tried to follow the instructions in this guide while translating them, and everything works fine, but the documentation is not updated lacks the Italian language and probably others!
I think we need to update the container.

**Comment by ambaradan** [comment]
Hi, I tried to run the tutorial in navigation.md as well, and it works, I managed to create a live copy on my system, but during the installation MkDocs also requested the mkdocs-redirects plugin which is not mentioned in the article.

**Comment by sspencerwire** [comment]
> Hi, I tried to run the tutorial in navigation.md as well, and it works, I managed to create a live copy on my system, but during the installation MkDocs also requested the mkdocs-redirects plugin which is not mentioned in the article.

You are correct. If you take a look at the mkdocs.yml file, it will show you the plugins under the "plugins:" section, even though those aren't necessarily the names of the python packages you need to install to get those. Feel free to push through a wording change on the document to include that plugin in the English version and then push a change to the Italian translations too.

**Comment by sspencerwire** [comment]
The content looks good as far as I can see. There is one spot that might be off in the admonitions, so I'm going to pull this into an editing branch and just take a look to make sure everything is OK.  Thanks again for your contributions!!  Just a note: We are working on a translation engine for our project using "Crowdin"... It's not ready to open up to translators as yet, but as soon as we have everything mapped out, documented, and working the way we want, I'll send you an invitation to use that platform for translations.

**Comment by ambaradan** [comment]
My mistake, I used the European format.
Europe - Day Month Year
America - Month Day Year
Sorry!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il lunedì 6 dicembre 2021 15:49, sspencerwire ***@***.***> ha scritto:

**Pull request merged**
