### PR TITLE
add 12-network.it.md

### PR DESCRIPTION
**Pull request by ambaradan**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@ambaradan Thank you so much for continuing your translations! I probably won't get to work this PR until Monday, so be patient and feel free to push other translations in the meantime.  Thanks again! Steve

**Comment by ambaradan** [comment]
No problem and good weekend

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il sabato 13 novembre 2021 16:58, sspencerwire ***@***.***> ha scritto:

**Comment by wsoyinka** [comment]
@ambaradan   -   Just a quick note to say a big thank you for your contributions  :-)

**Comment by ambaradan** [comment]
so from what I see the right way to have the translation in the admonitions is to enclose the translation itself between two double quotation marks

Example:
!!! Note " Aiuto alla memoria "

is that correct?

**Comment by sspencerwire** [comment]
> so from what I see the right way to have the translation in the admonitions is to enclose the translation itself between two double quotation marks
> 
> Example: !!! Note " Aiuto alla memoria "
> 
> is that correct?

@ambaradan You are correct. If you leave the Note (warning, tip, etc.) as it is, it will stay in English, but if you put in `Note "Nota"` then you will get that instead.

**Comment by sspencerwire** [comment]
Feel free to push through edits to fix whatever you like. Thanks again for your contributions!!!

**Pull request merged**
