### PR TITLE
03-commands.md: punctuation

### PR DESCRIPTION
**Pull request by SergeCroise**
- (e.g., ...)

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by SergeCroise** [comment]
@gannazhyrnova , @sspencerwire ,
please review
(feel free to modify or revert the changes).

**Review by gannazhyrnova — COMMENTED** [review]
I agree with the punctuation, but also there are also some other bugs. lines 132 - 144 - verbs must end with s (clears, checks and etc)

**Review by sspencerwire — COMMENTED** [review]
I'm not positive about the spaces added @SergeCroise My editor may complain about those, I'm not sure. I know it will complain about any added at the end of the line. I agree with the other change though.

**Comment by SergeCroise** [comment]
Hey, @gannazhyrnova , @sspencerwire ,
after reading how the command apropos works,
https://en.wikipedia.org/wiki/Apropos_(Unix)#Behavior
I believe it is better not to change (or translate) the apropos example in the article.
That is why, I close this PR.

**Pull request closed without merging**
