### PR TITLE
Updated the style guide a bit, and a proposal

### PR DESCRIPTION
**Pull request by EzequielBruni**
I updated the style guide a little based on some current practice/ideas, and finished up the unfinished bits. Finally. 

I'd like to make one more proposal, though, that I have not included. I'd like to officially propose, going forward, that every command that sits in its own "line" uses a code block, rather than inline code backticks. `code` in paragraphs can stay as-is of course, but I think everything that's not inline should officially go into a triple-backticked code block. If only so we can define the syntax.

To be clear, it should look like:

````markdown
Run this command:

```bash
the-command
```
````
And not:

````markdown
Run this command:

`the-command`
````

Thoughts?

### CODE REVIEW

**Comment by NezSez** [comment]
I like the idea of the syntax highlighting of the code blocks. So plus one thumbs!

**Comment by alemorvan** [comment]
For information and unfortunately, crowdin does not keep the bash after the 3 anti-quotes in the translations. We will open a way out occasionally.

**Comment by alemorvan** [comment]
@EzequielBruni could you add a note on admonitions? It might be interesting to add something like:

Add a note when you want to give a tip or information that you want to highlight. There are several types of admonitions (Note, Warning, Tip, etc.)

**Comment by sspencerwire** [comment]
After further thought @EzequielBruni I think single-line commands can be entered with the as:
```
this command is here
```
but the output of the command could include the ```bash if needed. As @antoine has said, Crowdin is not keeping the bash section of that code, so perhaps we should just ditch it altogether and go with what I just put above for the command for the output of the command as well.

**Comment by sspencerwire** [comment]
Also... I've not merged your changes (even though they can be merged), would you prefer to open an issue instead of keeping this conversation in the PR??

**Comment by EzequielBruni** [comment]
@sspencerwire Good point. Might be a better place to discuss it so we can merge the current changes.

I'd like to say that I don't think we need to be strict about keeping the language identifiers in translations and so on, my main concern was simple formatting.

**Pull request merged**
