### PR TITLE
po4a: generate pot files for guide/books and french locales.

### PR DESCRIPTION
**Pull request by alemorvan**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by alemorvan** [comment]
# Translation Tools

We need a workflow to help us track the status of translations of Rocky Linux documentation.

At the moment, a translator copies the source file (in English), renames it with the code for the language he will translate it for, and replaces the text with the text in his language.

This poses a big problem. If the source text is changed, this change is not reflected in the translated files.
If a translated file is modified, the source file does not benefit from the modifications made.
The sources and final documents are all mixed.

To solve this problem, we need to use a dedicated tool.

The principle of the workflow to be implemented is as follows:

* extract the strings from the source files (English version)
* generate a translation file of the strings for each target language
* recompile these translation files to obtain the final documentation.
* Each time the source files are modified, the strings must be extracted from the source files and the translation files updated.

!!! Warning
    All files that have already been translated will have to be manually re-translated.

The files containing the strings to be translated are `.pot` files (Portable Object Template). The files containing both the original strings and the translated strings are `.po` files (Portable Object - human readable) and `.mo` files (Machine Object - binary format).

Once the `.po`/`.mo` files are generated for each languages, translators can use tools like POEdit to make their work easier.

## Tooling

* I tried `python-sphinx` and `sphinx-intl` but they are made for REST format to translate into HTML, and that is not what we want. Sphinx tries to interpolate the markdown and gives bad results. It also needs a lot dependencies and the tooling is heavier than **po4a**.
* As Sphinx did not give me the result I wanted, I tested **po4a**, which is much simpler and quicker, it does the job I want.

Po4a is unable to work with all *.md files. We need to add each file to be translated in the po4a configuration file. This is good: as this way we keep control on what belong to the translation workflow (we won't lose what is translated at this time), and bad: each new translation need a manual add.

## Organization

Unlike a sphinx-based solution, we can keep our current organization: the source and translated documents remain in the `docs` folder, and po4a takes care of extracting the strings from this folder and recompiling the translated files alongside the originals.

!!! Warning
    Some files are manually translated, we need to take care of this.

## po4a configuration file

The configuration file is easy to understand.

You can configure the target language (need to be the same as mkdocs), the path to pot and locales po files and files to track (one line per file).

I chose to store all `.pot`, and `.po`/`.mo` files in a `locales` directory. The translated files stay located under docs/.

!!! Note
    MD files are managed as `text` type by po4a.

```
[po4a_langs] fr de jp
[po4a_paths] locales/gettext/$master.pot $lang:locales/po/$lang/$master.po
# documents to translate
# [type]	source				translation
[type:  text]	docs/books/admin_guide/00-toc.md	              $lang:docs/books/admin_guide/00-toc.$lang.md
[type:  text]	docs/books/admin_guide/01-presentation.md	      $lang:docs/books/admin_guide/01-presentation.$lang.md
...
```

With this configuration, a French translator will only have to work with files located under `locales/po/fr/`.

## Generating `.po` files and compiling translated files.

With only one command, each part of the process is done:

```
po4a -k0 po4a.conf                                           
```

I added the `-k0` option to force the compilation, even if there are no translated strings (the number is a percent, eq. we can accept to translate files when 80% of the content is translated for example).

You get the following working tree:

```
.
├── README.md
├── docs
│   ├── books
│   │   ├── admin_guide
│   │   │   ├── 00-toc.de.md
│   │   │   ├── 00-toc.fr.md
│   │   │   ├── 00-toc.jp.md
│   │   │   ├── 00-toc.md
│   │   │   ├── 01-presentation.de.md
│   │   │   ├── 01-presentation.fr.md
│   │   │   ├── 01-presentation.jp.md
│   │   │   ├── 01-presentation.md
│   │   │   ├── 03-commands.de.md
│   │   │   ├── 03-commands.fr.md
│   │   │   ├── 03-commands.jp.md
│   │   │   ├── 03-commands.md
│   │   │   ├── 04-advanced-commands.de.md
│   │   │   ├── 04-advanced-commands.fr.md
│   │   │   ├── 04-advanced-commands.jp.md
│   │   │   ├── 04-advanced-commands.md
...
│   └── guides
├── locales
│   ├── gettext
│   │   ├── 00-toc.md.pot
│   │   ├── 01-presentation.md.pot
│   │   ├── 03-commands.md.pot
│   │   └── 04-advanced-commands.md.pot
│   └── po
│       ├── de
│       │   ├── 00-toc.md.po
│       │   ├── 01-presentation.md.po
│       │   ├── 03-commands.md.po
│       │   └── 04-advanced-commands.md.po
│       ├── fr
│       │   ├── 00-toc.md.po
│       │   ├── 01-presentation.md.po
│       │   ├── 03-commands.md.po
│       │   └── 04-advanced-commands.md.po
│       └── jp
│           ├── 00-toc.md.po
│           ├── 01-presentation.md.po
│           ├── 03-commands.md.po
│           └── 04-advanced-commands.md.po
├── make.bat
└── po4a.conf

```

### Updating a source file

Here is an extract of the French translation file:

```
#. type: Plain text
#: docs/books/admin_guide/00-toc.md:2
msgid "# Learning Linux with Rocky"
msgstr "# Apprendre Linux avec Rocky"
```

This give us a translated file as follow:

```
# Apprendre Linux avec Rocky

```

Let's try to modify the source file:

```
# Learning Linux with Rocky8
```

The `po4a` command must be launched to track the change.

As the new text is not translated for the French version, the string is not translated anymore:

```
# Learning Linux with Rocky8
```

POEdit (for example), detect the modification and mark the string to be reviewed, and make a suggestion.

Once we have the po file to be modified, we can launch the `po4a` command again to get the French translated file with the new string.

## Dangers of the workflow

Contributors must stop modifying markdown files, otherwise their modifications would be lost.

We also have to work again on files that are already translated.

## Automation

For the moment, we can start working locally, but if this solution is kept, we will have to automate the process.

The `po4a` command needs to be launched at each push potentially on all branches.

We can also consider that the generation of locale files is the responsibility of an editor and that the generation of final files is the responsibility of a proofreader, in which case the automation process will only be available on the main branch.

## What's next

Once this process approved, we will be able to move to a web tool without loosing what is already completed.

**Comment by sspencerwire** [comment]
This PR adds new directories and tooling to the documentation workflow in an effort to help facilitate translations. Because it will change the footprint of the documentation significantly, I've requested @calderds , @EzequielBruni and @wsoyinka take a look at it and give it the once over. From an editing perspective, I've been through the introductory document once, but have not yet thoroughly edited it.  This added workflow would help with translations going forward. @alemorvan can answer any specific questions you have about it. Thanks for taking a look!

**Comment by justasojourner** [comment]
@alemorvan, hi can we have a discussion about translations - from the technical aspect as it affects the documentation source and with respect to capabilities and limitations of MkDocs and Material for MkDocs?

Not saying at all that I am an expert in translation software and platforms but interested to know how it works, what the possibilities are and help out if I can.

Also because @sspencerwire and I have made very significant changes to the documentation source files directory structure this current PR would very likely have to be reviewed.

**Comment by alemorvan** [comment]
We can now close this pull request, as we know now this solution will not be use.

**Pull request closed without merging**
