### PR TITLE
Install Mellanox OFED Drivers

### PR DESCRIPTION
**Pull request by jdhayes**
## Author checklist (to be completed by original Author)
- [X] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [X] Title and Author MetaTags have been inserted into the document 
- [X] If applicable, steps and instructions have been tested to work on a real system
- [X] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by calderds** [comment]
Hi Jordan, thanks for your contribution! I think it would be useful to have a paragraph at the top of the document describing what mellanox drivers are and why you might want to use them. Also, it would be nice to have another section at the beginning summarizing the commands you need to install these drivers without the verbose error explanation. Does that make sense? Thanks again!

**Comment by sspencerwire** [comment]
@jdhayes Do you have any interest in making some changes to the file as @calderds has suggested? I think it would be a good idea to clarify your document. I would like to add this document to a new category within the documentation "hardware and drivers"... The document really does need a little editing to get it to a stage where it would be ready to go. If you aren't interested, then I may pull it down, lab test it, and add the needed sections. If you can, let me know. Thanks for your submission!

**Comment by EzequielBruni** [comment]
@jdhayes Hey, that would be fantastic. We can wait.

**Comment by wsoyinka** [comment]
Hey @jdhayes    - Checking in for any updates on your testing ....

**Pull request closed without merging**
