### PR TITLE
Update beginners.md

### PR DESCRIPTION
**Pull request by SergeCroise**
* one-line and open-source (as adjectives) with hyphen
* punctuation

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@Grammaresque Could you look over these suggested changes to `beginners.md`?  If you agree with them, I'll merge them. Thank you!

**Comment by SergeCroise** [comment]
i am missing the nice little edit pencil on the documentation pages,
what is going on?
e.g.:
https://docs.rockylinux.org/guides/contribute/beginners/

**Comment by Grammaresque** [comment]
@SergeCroise re: "i am missing the nice little edit pencil on the documentation pages, what is going on?"

ahhh....I also do not see the pencil on this page or on any other one I checked. It was there before on another doc and I don't know what's different now, or if only some pages show that. Do you want to change that instruction to a true statement that actually gets the reader to the destination, or do you want me to? If there is a way to get directly to the editable version of whatever document one is reading, I would prefer that. But from what I know and see right now, I would say something like this under the Step 1. Start on the page you want to update: (sorry I don't know the conventional way developers would do a quote block in this box so I'll just use ***)

***
These instructions presuppose you have already created your GitHub account.

To find the editable version of this document, click the link in the upper-right corner of the page, which will take you to the GitHub documentation repository. Or follow this link: https://github.com/rocky-linux/documentation

Once there, open the folder called "docs" and search for this document. Its place in the tree matches its place in the tree on this page, and is named according to the URL of this page. For example, this specific page is in the folder docs > guides > contribute > beginners.

Choose the version of the doc with the extension .md (for main document). The rest are translations into our currently supported languages. **Note: If you'd like to contribute by helping us add new languages, skip everything else and just go introduce yourself in the Mattermost server right now.** (with a link to the documentation channel)

(unchanged, but in italics) The first time you contribute to the RL repository, you will be prompted with a green button to “Fork this repository and propose changes.” This creates a duplicate copy of the RL repository where you make your suggested edits. Simply click the green button and continue.
***

Actually, now that I understand the process better, I need to revise more than that. So I will be updating this doc again soon (sorry to make more work for you). The sections aren't in logical order, numbering is a mess (as @sspencerwire was trying to tell me and I lost sight of it), and some of the directions are not correct or adequate for a true first-timer, such as this one you noticed.

But your suggestions are a good iteration of this content. We should still continue with this PR.

**Review by Grammaresque — COMMENTED** [review]
These changes are good. I approve them.

**Review by sspencerwire — APPROVED** [review]

**Comment by sspencerwire** [comment]
@SergeCroise You are correct. The pencil no-longer appears and we actually wanted it that way from the very beginning, because we didn't want non-GitHub users to think that they could edit a page, only to be stymied by the fact that they didn't have an account. So the pencil does not exist. @Grammaresque I think that this can be a separate edit when you get to it, or @SergeCroise feel free to push that change through. Thank you both!

**Pull request merged**
