### PR TITLE
Updated for grammar and readability

### PR DESCRIPTION
**Pull request by HadManySons**
One notable change was, "You can also use and modify our example script implementing locking and full sync only when required." This was confusing as the sentence implied that this was available and free to use, but then defined some arbitrary "only when required" statement for its use. Changed this to, "if required."

## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by HadManySons** [comment]
Checklist items 2, 3, and 4 have been omitted because I don't believe they are applicable.

**Comment by sspencerwire** [comment]
@hbjydev @NeilHanlon Since I think you were both integral in the creation of this document, can you take a look at the suggested changes and make sure you don't have any issues with them? I'm not seeing anything from my point of view.  Thanks, Steve

**Comment by NeilHanlon** [comment]
lgtm

**Review by NeilHanlon — APPROVED** [review]

**Review by hbjydev — APPROVED** [review]
Lgtm

**Comment by sspencerwire** [comment]
Thanks for the additional comments. I'm merging. -- Steve

**Pull request merged**
