### PR TITLE
Improving the 9.2 release notes

### PR DESCRIPTION
**Pull request by lumarel**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [ ] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@lumarel Thanks for the improvements. Keep them coming. I've found that working on this from away from home while distracted with family things, is ... hard! :-)

**Comment by lumarel** [comment]
It's not finished rest comes when the build on my local end has finished and I find nothing else 😄

**Comment by lumarel** [comment]
@sspencerwire Little bit of restructure, removal of duplicates, false mentions and formatting, if you have anything to nit, just hit me up and I will fix it 👍🏻

**Comment by lumarel** [comment]
if you wondered, now it's ready ^^

**Review by sspencerwire — APPROVED** [review]
Thank you @lumarel

**Pull request merged**
