### PR TITLE
Correction of text meaning

### PR DESCRIPTION
**Pull request by jimcat8**
## Author checklist (to be completed by original Author)
- [ ] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
@jimcat8 You should make this change in Crowdin instead of here I think. Otherwise it will scramble the process.

**Comment by jimcat8** [comment]
> @jimcat8 You should make this change in Crowdin instead of here I think. Otherwise it will scramble the process.

It's only temporary.

**Comment by sspencerwire** [comment]
> > @jimcat8 You should make this change in Crowdin instead of here I think. Otherwise it will scramble the process.
> 
> It's only temporary.

@alemorvan Am I correct here that this should be done in Crowdin and not here?

**Comment by jimcat8** [comment]
It will take some time for these files to be translated to 100% progress.

**Comment by alemorvan** [comment]
> > > @jimcat8 You should make this change in Crowdin instead of here I think. Otherwise it will scramble the process.
> > 
> > 
> > It's only temporary.
> 
> @alemorvan Am I correct here that this should be done in Crowdin and not here?

Yes it is correct.

Crowdin will get the github modification and will send us a mail to inform that there are new translations.

**Comment by sspencerwire** [comment]
I'm closing this change. Crowdin should be used to fix this. Thanks!

**Pull request closed without merging**
