### PR TITLE
8_6_installation.md: improve grammar in a note in 8.6 install guide

### PR DESCRIPTION
**Pull request by zdover23**
Reword the English in a the note that directs the reader to the Rocky ISO mirrors, so that the note reads better.

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Comment by zdover23** [comment]
see also https://github.com/rocky-linux/documentation/pull/1503

**Review by sspencerwire — CHANGES_REQUESTED** [review]
These changes take up three separate lines, which I don't think was your intent. Also, the formatting should include the 4 spaces indent so that it fits as part of the note. See https://docs.rockylinux.org/guides/contribute/rockydocs_formatting/#admonitions for admonition formatting. Let me know if you have questions.

**Comment by zdover23** [comment]
> These changes take up three separate lines, which I don't think was your intent. Also, the formatting should include the 4 spaces indent so that it fits as part of the note. See https://docs.rockylinux.org/guides/contribute/rockydocs_formatting/#admonitions for admonition formatting. Let me know if you have questions.

My intention was to wrap the admonition at 80 lines, but my desire to conform to local standards is stronger than any desire to indulge my own preferences.

I've put this admonition on a single line now. I thought that I had included the four-space indent. Anyway, I haven't changed anything with respect to the four-space indent.

**Review by sspencerwire — APPROVED** [review]
Looks good! Thank you @zdover23

**Comment by sspencerwire** [comment]
@all-contributors add @zdover23 for content

**Pull request merged**
