### PR TITLE
Dev putta

### PR DESCRIPTION
**Pull request by theputta**
## Author checklist (to be completed by original Author)
- [x] Is this document a good fit for the Rocky project ?
- [ ] Is this a non-English contribution? 
- [ ] Title and Author MetaTags have been inserted into the document 
- [x] If applicable, steps and instructions have been tested to work on a real system
- [x] Did you perform an initial self-review to fix basic typos and grammatical correctness

## Rocky Documentation checklist  (to be completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] 5th Pass (Include document in TOC)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
Greetings again @theputta and thank you!  Changing the admonitions to emojis is really up to the original author. Also, this has never been done before on our site, so it would have to be tested to see if it is even possible to do. (depends on whether it is supported in Mkdocs or not). I will pull this down and take a look and then check with the original author to see if he wants to change the admonitions to emojis. I don't see any problems with the command changes. I won't get to this right away, but may be able to take a look later today or tomorrow morning.  Thanks again for your work!!  Steve

**Comment by theputta** [comment]
Thanks for the feedback about emojis. If accepted, I see that there are many changes to  be done to other files also. Looking forward to making those changes, if that's the route we are going on. 

Shall I send a new PR with just command changes to make your life a bit easy ?

**Comment by sspencerwire** [comment]
> Thanks for the feedback about emojis. If accepted, I see that there are many changes to be done to other files also. Looking forward to making those changes, if that's the route we are going on.
> 
> Shall I send a new PR with just command changes to make your life a bit easy ?

That's not necessary unless you want to. :-)  I can undo the emoji changes if needed. It will also give me a chance to "see" the emojis as I'm running a copy of Mkdocs locally that emulates the website. Thanks again for your contributions!!  Steve

**Comment by sspencerwire** [comment]
@alemorvan Do you want to take a look at this and see what you think about the changes? I don't think the emojis will work with mkdocs currently, so that's probably out, but take a look at the PR at your convenience and just review the suggested changes. Thanks, Steve

**Comment by sspencerwire** [comment]
@theputta Good day Aditya! The use of emojis works. However, the highlighting provided by the original admonitions (red for warning, blue for note, etc.) in this case is important to what the author wanted. The good news for you, however, is that the emojis **do** work, so if you have a document that you would like to submit yourself, you can certainly use these.

**Comment by alemorvan** [comment]
Hello @theputta. Thank you very much for this contribution. I'm adding my 👍 thumb as far as adding options is concerned, it's perfect. Regarding the replacement of admonitions by emojis, I confess I don't see the point.
We would lose all the syntactic advantage of html admonitions and the layout (which I think is pretty nice).

If you want to contribute on other documents, I suggest you for example to review the chapter on the network, which requires, in my opinion, a lot of complements (since the switch to systemd).

Thanks again!

**Pull request merged**
