### PR TITLE
Correct sha256sum invocation

### PR DESCRIPTION
**Pull request by alansill**
Avoid formatting error message when performing SHA256 check

#### Author checklist (Completed by original Author)
- [ ] Contribution a good fit for the Rocky project? Title and Author MetaTags inserted ?
- [ ] Is this a non-English contribution? 
- [ ] If applicable, steps and instructions have been tested to work on a real system
- [ ] Did you perform an initial self-review to fix basic typos and grammatical correctness

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Check that document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Basic Editorial Review)
- [ ] 4th Pass (Detailed Editorial Review and Peer Review)
- [ ] Final pass/approval (Final Review)

### CODE REVIEW

**Comment by alansill** [comment]
Still needs work.

**Comment by sspencerwire** [comment]
@alansill Not sure why you closed this... I was in the process of checking it and you are correct that the checksum does not display with the command included in the document and that your command syntax does, in fact, display the checksum. Both commands generate a syntax error of sorts on my Ubuntu machine... (yes, I know... Ubuntu)... 

Your command:

**Comment by sspencerwire** [comment]
@alansill please comment back... I'll hold this open until you respond.  Thanks!

**Comment by sspencerwire** [comment]
This works however:
```
sha256sum Rocky-8.5-x86_64-minimal.iso 
4eb2ae6b06876205f2209e4504110fe4115b37540c21ecfbbc0ebc11084cb779  Rocky-8.5-x86_64-minimal.iso
```

**Comment by sspencerwire** [comment]
Actually, I was taking this all out of context... that's my fault for not first looking at the document in its entirety. Once the checksum is downloaded the original command returns: 
```
sha256sum -c CHECKSUM --ignore-missing Rocky-8.5-x86_64-minimal.iso 
Rocky-8.5-x86_64-dvd1.iso: OK
Rocky-8.5-x86_64-minimal.iso: OK
sha256sum: Rocky-8.5-x86_64-minimal.iso: no properly formatted SHA256 checksum lines found
```
Which still returns that annoying last line after properly checking the checksum.

**Comment by alansill** [comment]
I think if you leave the iso file name off of the command it will check everything it can find as listed in the CHECKSUM file, so no need to include the file name.

**Comment by alansill** [comment]
> This works however:
> 
> ```
> sha256sum Rocky-8.5-x86_64-minimal.iso 
> 4eb2ae6b06876205f2209e4504110fe4115b37540c21ecfbbc0ebc11084cb779  Rocky-8.5-x86_64-minimal.iso
> ```

Do you have both the CHECKSUM file and the ISO file in the directory from which you issued the command? It works for me without the file name as I mentioned above if both files are present in the same directory.

**Comment by alansill** [comment]
In other words, this works for me:

v="8.5"; wget https://download.rockylinux.org/pub/rocky/$v/isos/x86_64/Rocky-$v-x86_64-minimal.iso; wget https://download.rockylinux.org/pub/rocky/$v/isos/x86_64/CHECKSUM; sha256sum -c CHECKSUM --ignore-missing

**Comment by alansill** [comment]
Closed and replaced by #664

**Pull request closed without merging**
