### PR TITLE
Suitable for RockyLinux 9 network configuration

### PR DESCRIPTION
**Pull request by Iuleoo**
#### Author checklist (Completed by original Author)
- [X] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [X] If applicable, steps and instructions have been tested to work
- [X] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [ ] 1st Pass (Document is good fit for project and author checklist completed)
- [ ] 2nd Pass (Technical Review - check for technical correctness) 
- [ ] 3rd Pass (Detailed Editorial Review and Peer Review)
- [ ] Final approval (Final Review)

### CODE REVIEW

**Comment by sspencerwire** [comment]
Hi @Iuleoo and thank you!  Unfortunately, we can't change the translated file, just the source (English) file.  It is then picked up and translated by our translation team and converted to the various languages. Are you able to change the English source document to what you are suggesting? (`basic_network_configuration.md`)

**Comment by SergeCroise** [comment]
hi @Iuleoo,
Thank you for your PR.
Do you have access to matermost ?
May be you have some interest to participate to our discussion about authoring in any language there:
https://chat.rockylinux.org/rocky-linux/channels/documentation
or here
https://chat.rockylinux.org/rocky-linux/channels/l10n

Au revoir !
Bis bald!

**Comment by Iuleoo** [comment]
> Hi @Iuleoo and thank you! Unfortunately, we can't change the translated file, just the source (English) file. It is then picked up and translated by our translation team and converted to the various languages. Are you able to change the English source document to what you are suggesting? (`basic_network_configuration.md`)
> 
> 嗨@Iuleoo，谢谢！ 遗憾的是，我们无法更改翻译后的文件，只能更改源（英文）文件。 然后由我们的翻译团队挑选并翻译成各种语言。 您能否将英文源文件更改为您建议的内容？ (basic_network_configuration.md)

Have modified the English document (basic_network_configuration.md) into a translated file, is this the right way to submit it?

**Comment by SergeCroise** [comment]
> > Hi @Iuleoo and thank you! Unfortunately, we can't change the translated file, just the source (English) file. It is then picked up and translated by our translation team and converted to the various languages. Are you able to change the English source document to what you are suggesting? (`basic_network_configuration.md`)
> > 嗨@Iuleoo，谢谢！ 遗憾的是，我们无法更改翻译后的文件，只能更改源（英文）文件。 然后由我们的翻译团队挑选并翻译成各种语言。 您能否将英文源文件更改为您建议的内容？ (basic_network_configuration.md)
> 
> Have modified the English document (basic_network_configuration.md) into a translated file, is this the right way to submit it?
@Iuleoo，谢谢
@Iuleoo, @sspencerwire, @wale, @alemorvan 
The new file basic_network_configuration.md could be a good a good start for a new item in our documentation.
I propose to store this new item at this place:
docs/new_articles/iuleoo/network/basic_network_configuration.md
or
docs/new_items/mandarin/iuleoo/network/basic_network_configuration.md
Iuleoo and the Rocky translator team, we could then organize the en-US part with crowdin.
What to you mean?

**Comment by wale** [comment]
Why did I get mentioned in this issue? I have no relation to Rocky Linux.

**Comment by SergeCroise** [comment]
> Why did I get mentioned in this issue? I have no relation to Rocky Linux.

hi @wale,
my mistake, thank you for noticing !

**Review by SergeCroise — CHANGES_REQUESTED** [review]
.

**Comment by Iuleoo** [comment]
> > > 嗨，谢谢！很遗憾，我们无法更改翻译后的文件，只能更改源（英语）文件。然后由我们的翻译团队拾取和翻译，并转换为各种语言。您是否能够将英文源文档更改为您的建议？（） 嗨，谢谢！ 遗憾的是，我们无法更改翻译后的文件，只能更改源（英文）文件。然后由我们的翻译团队挑选并翻译成各种语言。您能否将英文源文件更改为您建议的内容？ （basic_network_configuration.md）`basic_network_configuration.md`
> > 
> > 
> > 已将英文文档 （basic_network_configuration.md） 修改为翻译文件，这是提交文件的正确方式吗？ ，谢谢 ， ， ， 新文件 basic_network_configuration.md 可能是我们文档中新项目的良好开端。我建议将这个新项目存储在这个地方：docs/new_articles/iuleoo/network/basic_network_configuration.md 或 docs/new_items/mandarin/iuleoo/network/basic_network_configuration.md Iuleoo 和 Rocky 翻译团队，然后我们可以用 crowdin 组织 en-US 部分。 你是什么意思？



> > > Hi @Iuleoo and thank you! Unfortunately, we can't change the translated file, just the source (English) file. It is then picked up and translated by our translation team and converted to the various languages. Are you able to change the English source document to what you are suggesting? (`basic_network_configuration.md`)
> > > 嗨@Iuleoo，谢谢！ 遗憾的是，我们无法更改翻译后的文件，只能更改源（英文）文件。 然后由我们的翻译团队挑选并翻译成各种语言。 您能否将英文源文件更改为您建议的内容？ (basic_network_configuration.md)
> > 
> > 
> > Have modified the English document (basic_network_configuration.md) into a translated file, is this the right way to submit it?
> > @Iuleoo，谢谢
> > @Iuleoo, @sspencerwire, @wsoyinka, @alemorvan
> > The new file basic_network_configuration.md could be a good start for a new item in our documentation.
> > I suggest to store this new item at this place:
> > docs/new_articles/iuleoo/network/basic_network_configuration.md
> > or
> > docs/new_items/mandarin/iuleoo/network/basic_network_configuration.md
> > Iuleoo and the Rocky translator team, we could then organize the en-US part with crowdin.
> > What do you mean?

OK, I have modified the path as above, check if it is correct.
Better if you use crowdin

**Pull request closed without merging**
