### PR TITLE
Update mkdocs_venv.md

### PR DESCRIPTION
**Pull request by j0eybrinkman**
fixed typos - deacticate -> deactivate - 1127.0.0.1 -> 127.0.0.1

#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Review by sspencerwire — COMMENTED** [review]
@j0eybrinkman It looks like somehow you deleted the whole file and then re-added it. :-)  Can you verify that this is what you wanted?  Probably a better way would have been to just edit the section you wanted to fix. Do you want to try again?  I can close this PR... OR... I can merge it and then verify everything is OK afterward.

**Comment by j0eybrinkman** [comment]
@sspencerwire I'm not sure why but when I click the pencil icon then edit and make a commit it replaces the entire file. I'm not deleting the entire file so I am not sure why it is doing this.

**Comment by j0eybrinkman** [comment]
@sspencerwire Maybe this is why it is replacing the entire file? 
image

**Comment by sspencerwire** [comment]
> @sspencerwire Maybe this is why it is replacing the entire file? image

I'm not sure why it's doing that.  I know what you were trying to do, so if you like, I can just do it this time.

**Comment by sspencerwire** [comment]
> I'm not sure why it's doing that. I know what you were trying to do, so if you like, I can just do it this time.

What I should have done is tried to edit the file your way. I'm going to close my PR and try that.

**Comment by sspencerwire** [comment]
Reopening this one, as I had the same experience as you using the pencil edit method and I want to make sure it edits things OK.

**Review by sspencerwire — APPROVED** [review]

**Comment by sspencerwire** [comment]
@j0eybrinkman The file looks fine after merging. I've never seen that message before (until today), but merging didn't foul up the file at all. Thank you for your contribution!

**Comment by j0eybrinkman** [comment]
@sspencerwire Ofc, thank you!!

**Pull request merged**
