### PR TITLE
systemd hardening

### PR DESCRIPTION
**Pull request by hs303**
#### Author checklist (Completed by original Author)
- [x] Good fit for the Rocky Linux project? Title and Author Metatags inserted ?
- [x] If applicable, steps and instructions have been tested to work
- [x] Initial self-review to fix basic typos and grammar completed

#### Rocky Documentation checklist (Completed by Rocky team) 
- [x] 1st Pass (Document is good fit for project and author checklist completed)
- [x] 2nd Pass (Technical Review - check for technical correctness) 
- [x] 3rd Pass (Detailed Editorial Review and Peer Review)
- [x] Final approval (Final Review)

### CODE REVIEW

**Review by wsoyinka — DISMISSED** [review]
@hs303  -   My quick read through this guide was very enjoyable.  

Thank you for contributing this  :-) !

(p.s. I might recommend a slightly different title for the guide just so that it does not give the wrong impression that it's about hardening of the "systemd" sub-system itself.)

**Comment by hs303** [comment]
@wsoyinka thanks for the kind feedback. Indeed the title might be confusing. I've changed it to 'Systemd Units Hardening'.

**Review by sspencerwire — APPROVED** [review]
Thanks very much @hs303! This looks great! I'll run it through the editor.

**Comment by sspencerwire** [comment]
> @wsoyinka thanks for the kind feedback. Indeed the title might be confusing. I've changed it to 'Systemd Units Hardening'.

@hs303 did you mean to end up with two submissions in this PR?  There are two files one with the name you show here, and one with (what I think was) the original name. My guess is that you want to remove that one?  I can do that before it is merged, just let me know, or you can remove it yourself too.

**Comment by hs303** [comment]
Somehow I've messed it up by renaming the file. Could you please fix this @sspencerwire? Thanks!

**Comment by sspencerwire** [comment]
> Somehow I've messed it up by renaming the file. Could you please fix this @sspencerwire? Thanks!
I'll take care of it. Thank you again!

**Pull request merged**
